### ISSUE TITLE
Could not call public static ItemMeta deserialize(Map) throws IllegalArgumentException

### ISSUE THREAD

**Issue by PatPeter** [Multiverse/Multiverse-Inventories#159]
Here it is:

```
2013-03-24 15:34:37 [SEVERE] Could not call method 'public static org.bukkit.inventory.meta.ItemMeta org.bukkit.craftbukkit.v1_5_R2.inventory.CraftMetaItem$SerializableMeta.deserialize(java.util.Map) throws java.lang.Throwable' of class org.bukkit.craftbukkit.v1_5_R2.inventory.CraftMetaItem$SerializableMeta for deserialization
java.lang.IllegalArgumentException: color({}) is not a valid class org.bukkit.Color
    at org.bukkit.craftbukkit.v1_5_R2.inventory.CraftMetaItem$SerializableMeta.getObject(CraftMetaItem.java:167)
    at org.bukkit.craftbukkit.v1_5_R2.inventory.CraftMetaLeatherArmor.<init>(CraftMetaLeatherArmor.java:46)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:525)
    at org.bukkit.craftbukkit.v1_5_R2.inventory.CraftMetaItem$SerializableMeta.deserialize(CraftMetaItem.java:132)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeViaMethod(ConfigurationSerialization.java:73)
    at org.bukkit.configuration.serialization.ConfigurationSerialization.deserialize(ConfigurationSerialization.java:113)
    at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeObject(ConfigurationSerialization.java:187)
    at com.onarandombox.multiverseinventories.api.DataStrings$JSONItemWrapper.createItem(DataStrings.java:859)
    at com.onarandombox.multiverseinventories.api.DataStrings$JSONItemWrapper.<init>(DataStrings.java:835)
    at com.onarandombox.multiverseinventories.api.DataStrings$JSONItemWrapper.<init>(DataStrings.java:809)
    at com.onarandombox.multiverseinventories.api.DataStrings$ItemWrapper.wrap(DataStrings.java:672)
    at com.onarandombox.multiverseinventories.api.DataStrings.jsonParseInventory(DataStrings.java:434)
    at com.onarandombox.multiverseinventories.api.DataStrings.parseInventory(DataStrings.java:376)
    at com.onarandombox.multiverseinventories.api.share.InventorySerializer.deserialize(InventorySerializer.java:20)
    at com.onarandombox.multiverseinventories.api.share.InventorySerializer.deserialize(InventorySerializer.java:10)
    at com.onarandombox.multiverseinventories.util.data.DefaultPlayerProfile.<init>(DefaultPlayerProfile.java:67)
    at com.onarandombox.multiverseinventories.util.data.FlatFilePlayerData.getPlayerData(FlatFilePlayerData.java:241)
    at com.onarandombox.multiverseinventories.WeakProfileContainer.getPlayerData(WeakProfileContainer.java:98)
    at com.onarandombox.multiverseinventories.GameModeShareHandler.handle(GameModeShareHandler.java:47)
    at com.onarandombox.multiverseinventories.ShareHandler.handleSharing(ShareHandler.java:56)
    at com.onarandombox.multiverseinventories.InventoriesListener.playerGameModeChange(InventoriesListener.java:162)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:425)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
    at org.bukkit.plugin.TimedRegisteredListener.callEvent(TimedRegisteredListener.java:35)
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:477)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:462)
    at org.bukkit.craftbukkit.v1_5_R2.entity.CraftPlayer.setGameMode(CraftPlayer.java:550)
    at com.onarandombox.MultiverseCore.listeners.MVPlayerListener$2.run(MVPlayerListener.java:349)
    at org.bukkit.craftbukkit.v1_5_R2.scheduler.CraftTask.run(CraftTask.java:53)
    at org.bukkit.craftbukkit.v1_5_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:344)
    at net.minecraft.server.v1_5_R2.MinecraftServer.r(MinecraftServer.java:512)
    at net.minecraft.server.v1_5_R2.DedicatedServer.r(DedicatedServer.java:225)
    at net.minecraft.server.v1_5_R2.MinecraftServer.q(MinecraftServer.java:476)
    at net.minecraft.server.v1_5_R2.MinecraftServer.run(MinecraftServer.java:409)
    at net.minecraft.server.v1_5_R2.ThreadServerApplication.run(SourceFile:573)
```

**Comment by dumptruckman** [comment]
Pretty sure this is due to not using updated version or something.
