### ISSUE TITLE
The permission multiverse.inventories.info is already defined!

### ISSUE THREAD

**Issue by Joannou1** [Multiverse/Multiverse-Inventories#18]
`java.lang.IllegalArgumentException: The permission multiverse.inventories.info is already defined!`

I got the latest Dev versions of the plugin and Multiverse-Core.
The node is noowhere defined at all in the PEX file.

Full error:

```
[root@freshinstall ~]# screen -x GLD
14:07:42 [INFO] [Multiverse-Inventories] Loading Multiverse-Inventories v2.3-b37.
14:07:42 [SEVERE] Error occurred while enabling Multiverse-Inventories v2.3-b37 (Is it up to date?): The permission multiverse.inventories.info is already defined!
java.lang.IllegalArgumentException: The permission multiverse.inventories.info is already defined!
        at org.bukkit.plugin.SimplePluginManager.addPermission(SimplePluginManager.java:628)
        at com.onarandombox.multiverseinventories.permission.MVIPerms.register(MVIPerms.java:160)
        at com.onarandombox.multiverseinventories.MultiverseInventories.onEnable(MultiverseInventories.java:88)
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:230)
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:1057)
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:379)
        at im.mcft.pluginreloader.PluginReloader.loadPlugin(PluginReloader.java:226)
        at im.mcft.pluginreloader.PluginReloader.onCommand(PluginReloader.java:85)
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:40)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168)
        at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:386)
        at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:382)
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:574)
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:551)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:435)
        at net.minecraft.server.ThreadServerApplication.ru
```

Thanks.

**Comment by aycgit** [comment]
i have the same problem how did u fix this?
