### ISSUE TITLE
issue multiverse inventories

### ISSUE THREAD

**Issue by x4sTaTic** [Multiverse/Multiverse-Inventories#240]
[Server thread/ERROR]: Could not pass event PlayerChangedWorldEvent to Multiverse-Inventories v2.5-b335
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:294) ~[MINECRAFT1.7:git-Bukkit-1.7.2-R0.3-2-g85f5776-b3024jnks]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[MINECRAFT1.7:git-Bukkit-1.7.2-R0.3-2-g85f5776-b3024jnks]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [MINECRAFT1.7:git-Bukkit-1.7.2-R0.3-2-g85f5776-b3024jnks]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [MINECRAFT1.7:git-Bukkit-1.7.2-R0.3-2-g85f5776-b3024jnks]
    at net.minecraft.server.v1_7_R1.PlayerList.moveToWorld(PlayerList.java:526) [MINECRAFT1.7:git-Bukkit-1.7.2-R0.3-2-g85f5776-b3024jnks]
    at org.bukkit.craftbukkit.v1_7_R1.entity.CraftPlayer.teleport(CraftPlayer.java:467) [MINECRAFT1.7:git-Bukkit-1.7.2-R0.3-2-g85f5776-b3024jnks]
    at com.earth2me.essentials.Teleport.now(Teleport.java:126) [Essentials.jar:?]
    at com.earth2me.essentials.Teleport.now(Teleport.java:84) [Essentials.jar:?]
    at com.earth2me.essentials.spawn.Commandspawn.respawn(Commandspawn.java:64) [EssentialsSpawn.jar:?]
    at com.earth2me.essentials.spawn.Commandspawn.run(Commandspawn.java:52) [EssentialsSpawn.jar:?]
    at com.earth2me.esasdasdasdasdsentials.commands.EssentialsCommand.run(EssentialsCommand.java:161) [Essentials.jar:?]
    at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:501) [Essentials.jar:?]
    at com.earth2me.essentials.spawn.EssentialsSpawn.onCommand(EssentialsSpawn.java:72) [EssentialsSpawn.jar:?]
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [MINECRAFT1.7:git-Bukkit-1.7.2-R0.3-2-g85f5776-b3024jnks]
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:175) [MINECRAFT1.7:git-Bukkit-1.7.2-R0.3-2-g85f5776-b3024jnks]
    at net.minecraft.server.v1_7_R1.CommandBlockListenerAbstract.a(CommandBlockListenerAbstract.java:164) [MINECRAFT1.7:git-Bukkit-1.7.2-R0.3-2-g85f5776-b3024jnks]
    at net.minecraft.server.v1_7_R1.BlockCommand.a(BlockCommand.java:47) [MINECRAFT1.7:git-Bukkit-1.7.2-R0.3-2-g85f5776-b3024jnks]
    at net.minecraft.server.v1_7_R1.WorldServer.a(WorldServer.java:532) [MINECRAFT1.7:git-Bukkit-1.7.2-R0.3-2-g85f5776-b3024jnks]
    at net.minecraft.server.v1_7_R1.WorldServer.doTick(WorldServer.java:205) [MINECRAFT1.7:git-Bukkit-1.7.2-R0.3-2-g85f5776-b3024jnks]
    at net.minecraft.server.v1_7_R1.MinecraftServer.u(MinecraftServer.java:629) [MINECRAFT1.7:git-Bukkit-1.7.2-R0.3-2-g85f5776-b3024jnks]
    at net.minecraft.server.v1_7_R1.DedicatedServer.u(DedicatedServer.java:250) [MINECRAFT1.7:git-Bukkit-1.7.2-R0.3-2-g85f5776-b3024jnks]
    at net.minecraft.server.v1_7_R1.MinecraftServer.t(MinecraftServer.java:545) [MINECRAFT1.7:git-Bukkit-1.7.2-R0.3-2-g85f5776-b3024jnks]
    at net.minecraft.server.v1_7_R1.MinecraftServer.run(MinecraftServer.java:457) [MINECRAFT1.7:git-Bukkit-1.7.2-R0.3-2-g85f5776-b3024jnks]
    at net.minecraft.server.v1_7_R1.ThreadServerApplication.run(SourceFile:617) [MINECRAFT1.7:git-Bukkit-1.7.2-R0.3-2-g85f5776-b3024jnks]

**Comment by dumptruckman** [comment]
Not enough information to help with this. If still an issue, please open a new ticket with more detailed information.
