### ISSUE TITLE
NullPointerException in undefined context

### ISSUE THREAD

**Issue by Sabrucayore** [Multiverse/Multiverse-Inventories#243]
This is the bug i have since few days

[23:41:16 ERROR]: Could not call method 'public static org.bukkit.inventory.ItemStack org.bukkit.inventory.ItemStack.deserialize(java.util.Map)' of class org.bukkit.inventory.ItemStack for deserialization
java.lang.NullPointerException
at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:94) ~[ItemStack.class:git-Cauldron-MCPC-Plus-1.7.2-1.1147.04.107]
at org.bukkit.inventory.ItemStack.deserialize(ItemStack.java:528) ~[ItemStack.class:git-Cauldron-MCPC-Plus-1.7.2-1.1147.04.107]
at sun.reflect.GeneratedMethodAccessor138.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_55]
at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_55]
at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeViaMethod(ConfigurationSerialization.java:73) [ConfigurationSerialization.class:git-Cauldron-MCPC-Plus-1.7.2-1.1147.04.107]
at org.bukkit.configuration.serialization.ConfigurationSerialization.deserialize(ConfigurationSerialization.java:113) [ConfigurationSerialization.class:git-Cauldron-MCPC-Plus-1.7.2-1.1147.04.107]
at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeObject(ConfigurationSerialization.java:191) [ConfigurationSerialization.class:git-Cauldron-MCPC-Plus-1.7.2-1.1147.04.107]
at com.onarandombox.multiverseinventories.util.JsonConfiguration.dealWithSerializedObjects(JsonConfiguration.java:146) [Multiverse-Inventories-2.5.jar:?]
at com.onarandombox.multiverseinventories.util.JsonConfiguration.dealWithSerializedObjects(JsonConfiguration.java:137) [Multiverse-Inventories-2.5.jar:?]
at com.onarandombox.multiverseinventories.util.JsonConfiguration.dealWithSerializedObjects(JsonConfiguration.java:137) [Multiverse-Inventories-2.5.jar:?]
at com.onarandombox.multiverseinventories.util.JsonConfiguration.dealWithSerializedObjects(JsonConfiguration.java:137) [Multiverse-Inventories-2.5.jar:?]
at com.onarandombox.multiverseinventories.util.JsonConfiguration.convertMapsToSections(JsonConfiguration.java:115) [Multiverse-Inventories-2.5.jar:?]
at com.onarandombox.multiverseinventories.util.JsonConfiguration.loadFromString(JsonConfiguration.java:110) [Multiverse-Inventories-2.5.jar:?]
at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:149) [FileConfiguration.class:git-Cauldron-MCPC-Plus-1.7.2-1.1147.04.107]
at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:114) [FileConfiguration.class:git-Cauldron-MCPC-Plus-1.7.2-1.1147.04.107]
at com.onarandombox.multiverseinventories.util.JsonConfiguration.<init>(JsonConfiguration.java:184) [Multiverse-Inventories-2.5.jar:?]
at com.onarandombox.multiverseinventories.util.EncodedJsonConfiguration.<init>(EncodedJsonConfiguration.java:20) [Multiverse-Inventories-2.5.jar:?]
at com.onarandombox.multiverseinventories.util.data.FlatFilePlayerData.getConfigHandle(FlatFilePlayerData.java:77) [Multiverse-Inventories-2.5.jar:?]
at com.onarandombox.multiverseinventories.util.data.FlatFilePlayerData.processProfileWrite(FlatFilePlayerData.java:240) [Multiverse-Inventories-2.5.jar:?]
at com.onarandombox.multiverseinventories.util.data.FlatFilePlayerData.access$000(FlatFilePlayerData.java:30) [Multiverse-Inventories-2.5.jar:?]
at com.onarandombox.multiverseinventories.util.data.FlatFilePlayerData$FileWriteThread.run(FlatFilePlayerData.java:209) [Multiverse-Inventories-2.5.jar:?]

**Comment by dumptruckman** [comment]
Please open a new ticket with more detailed information about when the occurs if you're still having the problem.
