### ISSUE TITLE
An Internal Error ... 

### ISSUE THREAD

**Issue by vendola** [Multiverse/Multiverse-Inventories#247]
Hello guys, I.ve meet the same error several times. If someone can help me I'll be grateful

[01:43:28] [Server thread/WARN]: Unexpected exception while parsing console command "mvinv"
org.bukkit.command.CommandException: Unhandled exception executing command 'mvinv' in plugin Multiverse-Inventories v2.5-b335
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[euphoria.jar:git-Spigot-1649]
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) ~[euphoria.jar:git-Spigot-1649]
    at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:767) ~[euphoria.jar:git-Spigot-1649]
    at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchServerCommand(CraftServer.java:753) [euphoria.jar:git-Spigot-1649]
    at net.minecraft.server.v1_7_R4.DedicatedServer.aB(DedicatedServer.java:326) [euphoria.jar:git-Spigot-1649]
    at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:290) [euphoria.jar:git-Spigot-1649]
    at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584) [euphoria.jar:git-Spigot-1649]
    at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490) [euphoria.jar:git-Spigot-1649]
    at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [euphoria.jar:git-Spigot-1649]
Caused by: java.lang.NullPointerException
    at com.onarandombox.multiverseinventories.MultiverseInventories.onCommand(MultiverseInventories.java:215) ~[?:?]
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[euphoria.jar:git-Spigot-1649]
    ... 8 more

**Comment by dumptruckman** [comment]
Not enough information to do anything with this. Please open a new ticket if still having this problem.
