### ISSUE TITLE
Invalid JSON detected

### ISSUE THREAD

**Issue by someone-somenet-org** [Multiverse/Multiverse-Inventories#265]
Hi, im getting a weird exception in my server logs.
It does not seem to be affecting me in any way, but its an exception so better take a look at it :)

It happens every time when i do: /mv tp world

cat plugins/Multiverse-Inventories/worlds/world/someone.json
{"CREATIVE":{"enderChestContents":{},"inventoryContents":{},"armorContents":{},"potions":"[]","stats":{"ex":"0.0","ra":"300","hp":"20.0","txp":"0","fl":"20","el":"0","ma":"300","sa":"5.0","xp":"0.0","ft":"0","fd":"0.0"}}}

spigot 1.8.3
Multiverse-Core v2.5-b688
Multiverse-Inventories v2.5-b383

*\* the exception **

```
[02:48:13] [MV-Inv Profile Write Thread/ERROR]: Cannot load plugins/Multiverse-Inventories/worlds/world/someone.json
org.bukkit.configuration.InvalidConfigurationException: Invalid JSON detected.
        at com.onarandombox.multiverseinventories.util.JsonConfiguration.loadFromString(JsonConfiguration.java:104) ~[?:?]
        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:226) ~[spigot.jar:git-Spigot-9284e9b-7722428]
        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:169) ~[spigot.jar:git-Spigot-9284e9b-7722428]
        at com.onarandombox.multiverseinventories.util.JsonConfiguration.<init>(JsonConfiguration.java:184) [Multiverse-Inventories-2.5-b383.jar:?]
        at com.onarandombox.multiverseinventories.util.EncodedJsonConfiguration.<init>(EncodedJsonConfiguration.java:20) [Multiverse-Inventories-2.5-b383.jar:
?]
        at com.onarandombox.multiverseinventories.util.data.FlatFilePlayerData.getConfigHandle(FlatFilePlayerData.java:77) [Multiverse-Inventories-2.5-b383.ja
r:?]
        at com.onarandombox.multiverseinventories.util.data.FlatFilePlayerData.processProfileWrite(FlatFilePlayerData.java:240) [Multiverse-Inventories-2.5-b3
83.jar:?]
        at com.onarandombox.multiverseinventories.util.data.FlatFilePlayerData.access$000(FlatFilePlayerData.java:30) [Multiverse-Inventories-2.5-b383.jar:?]
        at com.onarandombox.multiverseinventories.util.data.FlatFilePlayerData$FileWriteThread.run(FlatFilePlayerData.java:209) [Multiverse-Inventories-2.5-b3
83.jar:?]
[02:48:13] [MV-Inv Profile Write Thread/ERROR]: Cannot load plugins/Multiverse-Inventories/groups/world/someone.json
org.bukkit.configuration.InvalidConfigurationException: Invalid JSON detected.
        at com.onarandombox.multiverseinventories.util.JsonConfiguration.loadFromString(JsonConfiguration.java:104) ~[?:?]
        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:226) ~[spigot.jar:git-Spigot-9284e9b-7722428]
        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:169) ~[spigot.jar:git-Spigot-9284e9b-7722428]
        at com.onarandombox.multiverseinventories.util.JsonConfiguration.<init>(JsonConfiguration.java:184) [Multiverse-Inventories-2.5-b383.jar:?]
        at com.onarandombox.multiverseinventories.util.EncodedJsonConfiguration.<init>(EncodedJsonConfiguration.java:20) [Multiverse-Inventories-2.5-b383.jar:
?]
        at com.onarandombox.multiverseinventories.util.data.FlatFilePlayerData.getConfigHandle(FlatFilePlayerData.java:77) [Multiverse-Inventories-2.5-b383.ja
r:?]
        at com.onarandombox.multiverseinventories.util.data.FlatFilePlayerData.processProfileWrite(FlatFilePlayerData.java:240) [Multiverse-Inventories-2.5-b3
83.jar:?]
        at com.onarandombox.multiverseinventories.util.data.FlatFilePlayerData.access$000(FlatFilePlayerData.java:30) [Multiverse-Inventories-2.5-b383.jar:?]
        at com.onarandombox.multiverseinventories.util.data.FlatFilePlayerData$FileWriteThread.run(FlatFilePlayerData.java:209) [Multiverse-Inventories-2.5-b3
83.jar:?]
```

**Comment by runelynx** [comment]
Same happens to me all the time

**Comment by TheIntelloBox** [comment]
Same

**Comment by dumptruckman** [comment]
Please refer to the bold important message at the top of the plugin page https://dev.bukkit.org/projects/multiverse-inventories

**Comment by runelynx** [comment]
Closing the topic is fine, I uninstalled this plugin over the weekend.

**Comment by dumptruckman** [comment]
This may be fixed now. The data you showed does not look like the data that caused the same exception elsewhere though...

**Comment by benwoo1110** [comment]
There isn't reports of such an issue on latest versions of mv-inv. So will be closing the issue. Do feel free to open a new issue if needed, thanks!
