### ISSUE TITLE
Problem with multiverse-inventories

### ISSUE THREAD

**Issue by arceus69** [Multiverse/Multiverse-Inventories#271]
Hi,

I'm using Multiverse-Inventories v2.5-b385 in an RPG/Faction server. In my RPG worlds the players have more than the basic health and everytime they return in a world where the health are the default of minecraft, i get this error in console:

Could not pass event PlayerChangedWorldEvent to Multiverse-Inventories v2.5-b385
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[server.jar:git-Spigot-044d928-e8c6403]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-Spigot-044d928-e8c6403]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [server.jar:git-Spigot-044d928-e8c6403]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [server.jar:git-Spigot-044d928-e8c6403]
	at net.minecraft.server.v1_8_R3.PlayerList.moveToWorld(PlayerList.java:623) [server.jar:git-Spigot-044d928-e8c6403]
	at org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.teleport(CraftPlayer.java:475) [server.jar:git-Spigot-044d928-e8c6403]
	at com.earth2me.essentials.Teleport.now(Teleport.java:126) [Essentials-2.x-SNAPSHOT.jar:?]
	at com.earth2me.essentials.Teleport.teleport(Teleport.java:194) [Essentials-2.x-SNAPSHOT.jar:?]
	at com.earth2me.essentials.Teleport.warp(Teleport.java:263) [Essentials-2.x-SNAPSHOT.jar:?]
	at com.earth2me.essentials.signs.SignWarp.onSignInteract(SignWarp.java:61) [Essentials-2.x-SNAPSHOT.jar:?]
	at com.earth2me.essentials.signs.EssentialsSign.onSignInteract(EssentialsSign.java:119) [Essentials-2.x-SNAPSHOT.jar:?]
	at com.earth2me.essentials.signs.SignPlayerListener.onSignPlayerInteract(SignPlayerListener.java:75) [Essentials-2.x-SNAPSHOT.jar:?]
	at sun.reflect.GeneratedMethodAccessor222.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) [server.jar:git-Spigot-044d928-e8c6403]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [server.jar:git-Spigot-044d928-e8c6403]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [server.jar:git-Spigot-044d928-e8c6403]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [server.jar:git-Spigot-044d928-e8c6403]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:227) [server.jar:git-Spigot-044d928-e8c6403]
	at net.minecraft.server.v1_8_R3.PlayerInteractManager.interact(PlayerInteractManager.java:463) [server.jar:git-Spigot-044d928-e8c6403]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:736) [server.jar:git-Spigot-044d928-e8c6403]
	at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:52) [server.jar:git-Spigot-044d928-e8c6403]
	at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1) [server.jar:git-Spigot-044d928-e8c6403]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [server.jar:git-Spigot-044d928-e8c6403]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.7.0]
	at java.util.concurrent.FutureTask$Sync.innerRun(Unknown Source) [?:1.7.0]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.7.0]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SystemUtils.java:19) [server.jar:git-Spigot-044d928-e8c6403]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:718) [server.jar:git-Spigot-044d928-e8c6403]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:367) [server.jar:git-Spigot-044d928-e8c6403]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:657) [server.jar:git-Spigot-044d928-e8c6403]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560) [server.jar:git-Spigot-044d928-e8c6403]
	at java.lang.Thread.run(Unknown Source) [?:1.7.0]
Caused by: java.lang.IllegalArgumentException: Health must be between 0 and 10.0
	at org.bukkit.craftbukkit.v1_8_R3.entity.CraftLivingEntity.setHealth(CraftLivingEntity.java:83) ~[server.jar:git-Spigot-044d928-e8c6403]
	at com.onarandombox.multiverseinventories.api.share.Sharables$7.updatePlayer(Sharables.java:177) ~[?:?]
	at com.onarandombox.multiverseinventories.ShareHandler.updatePlayer(ShareHandler.java:140) ~[?:?]
	at com.onarandombox.multiverseinventories.ShareHandler.completeSharing(ShareHandler.java:89) ~[?:?]
	at com.onarandombox.multiverseinventories.ShareHandler.handleSharing(ShareHandler.java:60) ~[?:?]
	at com.onarandombox.multiverseinventories.InventoriesListener.playerChangedWorld(InventoriesListener.java:183) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor573.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[server.jar:git-Spigot-044d928-e8c6403]
	... 33 more

The real problem of that error is the inventories, when they get this error, the inventories from RPG worlds remains the same after changing world and if in the other inventories there's something, it overwrite with the RPG inventories. There's something to resolve this issues?

**Comment by dumptruckman** [comment]
Something you are using is trying to set a player's health above or below a legal value. Therefore when Multiverse-Inventories tries to make these changes the server denies them with an exception. You can set your MV-Inv group to not share health and that should solve the problem. It also means you won't have different health values for each world group.
