### ISSUE TITLE
Could not parse item: ItemStack{IRON_BOOTS x 1}

### ISSUE THREAD

**Issue by bcurtiswx** [Multiverse/Multiverse-Inventories#288]
Not sure what other info you may need. Let me know.

This happens on occasion with certain items.

`[11:19:24] [Server thread/WARN]: [Multiverse-Inventories] Invalid key: 40 while parsing inventory
[11:19:24] [Server thread/WARN]: java.lang.ArrayIndexOutOfBoundsException: 36
[11:19:24] [Server thread/WARN]:    at com.onarandombox.multiverseinventories.api.DataStrings.parseInventory(DataStrings.java:421)
[11:19:24] [Server thread/WARN]:    at com.onarandombox.multiverseinventories.api.share.InventorySerializer.deserialize(InventorySerializer.java:20)
[11:19:24] [Server thread/WARN]:    at com.onarandombox.multiverseinventories.api.share.InventorySerializer.deserialize(InventorySerializer.java:10)
[11:19:24] [Server thread/WARN]:    at com.onarandombox.multiverseinventories.util.data.DefaultPlayerProfile.<init>(DefaultPlayerProfile.java:76)
[11:19:24] [Server thread/WARN]:    at com.onarandombox.multiverseinventories.util.data.FlatFilePlayerData.getPlayerData(FlatFilePlayerData.java:283)
[11:19:24] [Server thread/WARN]:    at com.onarandombox.multiverseinventories.WeakProfileContainer.getPlayerData(WeakProfileContainer.java:98)
[11:19:24] [Server thread/WARN]:    at com.onarandombox.multiverseinventories.WeakProfileContainer.getPlayerData(WeakProfileContainer.java:87)
[11:19:24] [Server thread/WARN]:    at com.onarandombox.multiverseinventories.WorldChangeShareHandler.handle(WorldChangeShareHandler.java:33)
[11:19:24] [Server thread/WARN]:    at com.onarandombox.multiverseinventories.ShareHandler.handleSharing(ShareHandler.java:56)
[11:19:24] [Server thread/WARN]:    at com.onarandombox.multiverseinventories.InventoriesListener.playerChangedWorld(InventoriesListener.java:183)
[11:19:24] [Server thread/WARN]:    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[11:19:24] [Server thread/WARN]:    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
[11:19:24] [Server thread/WARN]:    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[11:19:24] [Server thread/WARN]:    at java.lang.reflect.Method.invoke(Method.java:606)
[11:19:24] [Server thread/WARN]:    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
[11:19:24] [Server thread/WARN]:    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[11:19:24] [Server thread/WARN]:    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
[11:19:24] [Server thread/WARN]:    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
[11:19:24] [Server thread/WARN]:    at net.minecraft.server.v1_9_R1.PlayerList.moveToWorld(PlayerList.java:684)
[11:19:24] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_9_R1.entity.CraftPlayer.teleport(CraftPlayer.java:468)
[11:19:24] [Server thread/WARN]:    at com.earth2me.essentials.Teleport.now(Teleport.java:126)
[11:19:24] [Server thread/WARN]:    at com.earth2me.essentials.Teleport.teleport(Teleport.java:194)
[11:19:24] [Server thread/WARN]:    at com.earth2me.essentials.Teleport.teleport(Teleport.java:142)
[11:19:24] [Server thread/WARN]:    at com.earth2me.essentials.commands.Commandhome.goHome(Commandhome.java:127)
[11:19:24] [Server thread/WARN]:    at com.earth2me.essentials.commands.Commandhome.run(Commandhome.java:76)
[11:19:24] [Server thread/WARN]:    at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:180)
[11:19:24] [Server thread/WARN]:    at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:527)
[11:19:24] [Server thread/WARN]:    at com.earth2me.essentials.Essentials.onCommand(Essentials.java:402)
[11:19:24] [Server thread/WARN]:    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[11:19:24] [Server thread/WARN]:    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[11:19:24] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchCommand(CraftServer.java:645)
[11:19:24] [Server thread/WARN]:    at net.minecraft.server.v1_9_R1.PlayerConnection.handleCommand(PlayerConnection.java:1342)
[11:19:24] [Server thread/WARN]:    at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1177)
[11:19:24] [Server thread/WARN]:    at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[11:19:24] [Server thread/WARN]:    at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
[11:19:24] [Server thread/WARN]:    at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[11:19:24] [Server thread/WARN]:    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
[11:19:24] [Server thread/WARN]:    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
[11:19:24] [Server thread/WARN]:    at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45)
[11:19:24] [Server thread/WARN]:    at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:721)
[11:19:24] [Server thread/WARN]:    at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400)
[11:19:24] [Server thread/WARN]:    at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660)
[11:19:24] [Server thread/WARN]:    at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559)
[11:19:24] [Server thread/WARN]:    at java.lang.Thread.run(Thread.java:745)
[11:19:24] [Server thread/WARN]: [Multiverse-Inventories] Could not parse item: ItemStack{IRON_BOOTS x 1}
[11:19:24] [Server thread/WARN]: [Multiverse-Inventories] Invalid key: 39 while parsing inventory
[11:19:24] [Server thread/WARN]: [Multiverse-Inventories] Invalid key: 37 while parsing inventory
[11:19:24] [Server thread/WARN]: [Multiverse-Inventories] Invalid key: 38 while parsing inventory
`

**Comment by bcurtiswx** [comment]
http://paste.ubuntu.com/15414530/

**Comment by dumptruckman** [comment]
I'd recommend giving [PWI](https://www.spigotmc.org/resources/per-world-inventory.4482/) a look as we're not supporting Multiverse-Inventories at this time due to time constraints of the developers and it has several known issues.

PWI supports importing your Multiverse-Inventories settings.

I would only suggest using another plugin if it was open source, and [PWI is](https://bitbucket.org/Gnat008/perworldinventory/overview).

**Comment by dumptruckman** [comment]
Kinda seems related to #296. May investigate.
