### ISSUE TITLE
Console Error when travel to another world

### ISSUE THREAD

**Issue by antidust** [Multiverse/Multiverse-Inventories#292]
everything works fine just console error

[10:47:16 INFO]: UUID of player antidust is ea4ca185-ca16-3392-9ff6-b583f1c219ba

[10:47:16 INFO]: antidust[activate.adobe.com/127.0.0.1:49938] logged in with ent
ity id 1030 at ([basic]-533.218948646721, 64.0, 342.01396299846846)
[10:47:23 INFO]: antidust issued server command: /i diamond
[10:47:25 INFO]: antidust issued server command: /enderchest
[10:47:32 INFO]: antidust issued server command: /warp secret
[10:47:32 ERROR]: Cannot load plugins\Multiverse-Inventories\worlds\basic\antidu
st.json
org.bukkit.configuration.InvalidConfigurationException: Invalid JSON detected.
        at com.onarandombox.multiverseinventories.util.JsonConfiguration.loadFro
mString(JsonConfiguration.java:104) ~[?:?]
        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguratio
n.java:184) ~[spigot.jar:git-Spigot-d20369f-7fc5cd8]
        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguratio
n.java:130) ~[spigot.jar:git-Spigot-d20369f-7fc5cd8]
        at com.onarandombox.multiverseinventories.util.JsonConfiguration.<init>(
JsonConfiguration.java:184) [Multiverse-Inventories-2.5.jar:?]
        at com.onarandombox.multiverseinventories.util.EncodedJsonConfiguration.
<init>(EncodedJsonConfiguration.java:20) [Multiverse-Inventories-2.5.jar:?]
        at com.onarandombox.multiverseinventories.util.data.FlatFilePlayerData.g
etConfigHandle(FlatFilePlayerData.java:77) [Multiverse-Inventories-2.5.jar:?]
        at com.onarandombox.multiverseinventories.util.data.FlatFilePlayerData.g
etPlayerData(FlatFilePlayerData.java:269) [Multiverse-Inventories-2.5.jar:?]
        at com.onarandombox.multiverseinventories.WeakProfileContainer.getPlayer
Data(WeakProfileContainer.java:98) [Multiverse-Inventories-2.5.jar:?]
        at com.onarandombox.multiverseinventories.WeakProfileContainer.getPlayer
Data(WeakProfileContainer.java:87) [Multiverse-Inventories-2.5.jar:?]
        at com.onarandombox.multiverseinventories.InventoriesListener.playerTele
port(InventoriesListener.java:203) [Multiverse-Inventories-2.5.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0
_77]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0
_77]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1
.8.0_77]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_77]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.ja
va:306) [spigot.jar:git-Spigot-d20369f-7fc5cd8]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.jav
a:62) [spigot.jar:git-Spigot-d20369f-7fc5cd8]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.j
ava:502) [spigot.jar:git-Spigot-d20369f-7fc5cd8]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.j
ava:487) [spigot.jar:git-Spigot-d20369f-7fc5cd8]
        at org.bukkit.craftbukkit.v1_9_R1.entity.CraftPlayer.teleport(CraftPlaye
r.java:441) [spigot.jar:git-Spigot-d20369f-7fc5cd8]
        at com.earth2me.essentials.Teleport.now(Teleport.java:126) [Essentials-2
.x-SNAPSHOT.jar:?]
        at com.earth2me.essentials.Teleport.teleport(Teleport.java:194) [Essenti
als-2.x-SNAPSHOT.jar:?]
        at com.earth2me.essentials.Teleport.warp(Teleport.java:263) [Essentials-
2.x-SNAPSHOT.jar:?]
        at com.earth2me.essentials.commands.Commandwarp.warpUser(Commandwarp.jav
a:130) [Essentials-2.x-SNAPSHOT.jar:?]
        at com.earth2me.essentials.commands.Commandwarp.run(Commandwarp.java:51)
 [Essentials-2.x-SNAPSHOT.jar:?]
        at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsComm
and.java:180) [Essentials-2.x-SNAPSHOT.jar:?]
        at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.jav
a:527) [Essentials-2.x-SNAPSHOT.jar:?]
        at com.earth2me.essentials.Essentials.onCommand(Essentials.java:402) [Es
sentials-2.x-SNAPSHOT.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [spig
ot.jar:git-Spigot-d20369f-7fc5cd8]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:14
1) [spigot.jar:git-Spigot-d20369f-7fc5cd8]
        at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchCommand(CraftServe
r.java:645) [spigot.jar:git-Spigot-d20369f-7fc5cd8]
        at net.minecraft.server.v1_9_R1.PlayerConnection.handleCommand(PlayerCon
nection.java:1350) [spigot.jar:git-Spigot-d20369f-7fc5cd8]
        at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java
:1185) [spigot.jar:git-Spigot-d20369f-7fc5cd8]
        at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java
:45) [spigot.jar:git-Spigot-d20369f-7fc5cd8]
        at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java
:1) [spigot.jar:git-Spigot-d20369f-7fc5cd8]
        at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:1
3) [spigot.jar:git-Spigot-d20369f-7fc5cd8]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [
?:1.8.0_77]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_77]
        at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [spigot.jar
:git-Spigot-d20369f-7fc5cd8]
        at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:7
21) [spigot.jar:git-Spigot-d20369f-7fc5cd8]
        at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:4
00) [spigot.jar:git-Spigot-d20369f-7fc5cd8]
        at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:6
60) [spigot.jar:git-Spigot-d20369f-7fc5cd8]
        at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java
:559) [spigot.jar:git-Spigot-d20369f-7fc5cd8]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_77]
[10:47:33 ERROR]: Cannot load plugins\Multiverse-Inventories\worlds\basic\antidu
st.json
org.bukkit.configuration.InvalidConfigurationException: Invalid JSON detected.
        at com.onarandombox.multiverseinventories.util.JsonConfiguration.loadFro
mString(JsonConfiguration.java:104) ~[?:?]
        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguratio
n.java:184) ~[spigot.jar:git-Spigot-d20369f-7fc5cd8]
        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguratio
n.java:130) ~[spigot.jar:git-Spigot-d20369f-7fc5cd8]
        at com.onarandombox.multiverseinventories.util.JsonConfiguration.<init>(
JsonConfiguration.java:184) [Multiverse-Inventories-2.5.jar:?]
        at com.onarandombox.multiverseinventories.util.EncodedJsonConfiguration.
<init>(EncodedJsonConfiguration.java:20) [Multiverse-Inventories-2.5.jar:?]
        at com.onarandombox.multiverseinventories.util.data.FlatFilePlayerData.g
etConfigHandle(FlatFilePlayerData.java:77) [Multiverse-Inventories-2.5.jar:?]
        at com.onarandombox.multiverseinventories.util.data.FlatFilePlayerData.p
rocessProfileWrite(FlatFilePlayerData.java:240) [Multiverse-Inventories-2.5.jar:
?]
        at com.onarandombox.multiverseinventories.util.data.FlatFilePlayerData.a
ccess$000(FlatFilePlayerData.java:30) [Multiverse-Inventories-2.5.jar:?]
        at com.onarandombox.multiverseinventories.util.data.FlatFilePlayerData$F
ileWriteThread.run(FlatFilePlayerData.java:209) [Multiverse-Inventories-2.5.jar:
?]

**Comment by matcracker** [comment]
Same problem!

**Comment by dumptruckman** [comment]
Multiverse-Inventories is no longer being maintained. We have found a good replacement that even supports importing your inventories from MV-Inventories: [PWI](https://www.spigotmc.org/resources/per-world-inventory.4482/)
