### ISSUE TITLE
Error on disable

### ISSUE THREAD

**Issue by EvilOlaf** [Multiverse/Multiverse-Inventories#295]
```
[18:07:42] [Server thread/INFO]: [Multiverse-Inventories] Disabling Multiverse-Inventories v2.5-b408
[18:07:42] [Server thread/ERROR]: Error occurred while disabling Multiverse-Inventories v2.5-b408 (Is it up to date?)
Java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player;
        at com.onarandombox.multiverseinventories.MultiverseInventories.onDisable(MultiverseInventories.java:76) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:294) ~[spigot-1.9.2.jar:git-Spigot-5a40365-f631379]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:364) [spigot-1.9.2.jar:git-Spigot-5a40365-f631379]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:424) [spigot-1.9.2.jar:git-Spigot-5a40365-f631379]
        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:417) [spigot-1.9.2.jar:git-Spigot-5a40365-f631379]
        at org.bukkit.craftbukkit.v1_9_R1.CraftServer.disablePlugins(CraftServer.java:340) [spigot-1.9.2.jar:git-Spigot-5a40365-f631379]
        at net.minecraft.server.v1_9_R1.MinecraftServer.stop(MinecraftServer.java:454) [spigot-1.9.2.jar:git-Spigot-5a40365-f631379]
        at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:595) [spigot-1.9.2.jar:git-Spigot-5a40365-f631379]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_77]
```

Core build 719
Inv build 408
git-Spigot-5a40365-f631379 (MC: 1.9.2)

**Comment by LezChap** [comment]
https://github.com/Multiverse/Multiverse-Inventories/issues/291#issuecomment-205372865

^ Noticed this, but not after a good 30-45 minutes testing and getting logs ready...Dumptruckman, could you please update the readme.md for this repository, and the wiki page for this plugin to include the fact that this project is no longer being maintained and the recommended replacement?

**Comment by dumptruckman** [comment]
Updated readme and wiki
