### ISSUE TITLE
Error with Custom Enchantments

### ISSUE THREAD

**Issue by GenerationMC** [Multiverse/Multiverse-Inventories#299]
Hi I am getting this error whenever we have an item in inventory that has a custom enchantment on:

13.09 21:09:51 [Server] WARN java.lang.ArrayIndexOutOfBoundsException: 36
13.09 21:09:51 [Server] WARN at com.onarandombox.multiverseinventories.api.DataStrings.parseInventory(DataStrings.java:421)
13.09 21:09:51 [Server] WARN at com.onarandombox.multiverseinventories.api.share.InventorySerializer.deserialize(InventorySerializer.java:20)
13.09 21:09:51 [Server] WARN at com.onarandombox.multiverseinventories.api.share.InventorySerializer.deserialize(InventorySerializer.java:10)
13.09 21:09:51 [Server] WARN at com.onarandombox.multiverseinventories.util.data.DefaultPlayerProfile.<init>(DefaultPlayerProfile.java:76)
13.09 21:09:51 [Server] WARN at com.onarandombox.multiverseinventories.util.data.FlatFilePlayerData.getPlayerData(FlatFilePlayerData.java:283)
13.09 21:09:51 [Server] WARN at com.onarandombox.multiverseinventories.WeakProfileContainer.getPlayerData(WeakProfileContainer.java:98)
13.09 21:09:51 [Server] WARN at com.onarandombox.multiverseinventories.WeakProfileContainer.getPlayerData(WeakProfileContainer.java:87)
13.09 21:09:51 [Server] WARN at com.onarandombox.multiverseinventories.WorldChangeShareHandler.handle(WorldChangeShareHandler.java:33)
13.09 21:09:51 [Server] WARN at com.onarandombox.multiverseinventories.ShareHandler.handleSharing(ShareHandler.java:56)
13.09 21:09:51 [Server] WARN at com.onarandombox.multiverseinventories.InventoriesListener.playerChangedWorld(InventoriesListener.java:183)
13.09 21:09:51 [Server] WARN at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
13.09 21:09:51 [Server] WARN at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
13.09 21:09:51 [Server] WARN at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
13.09 21:09:51 [Server] WARN at java.lang.reflect.Method.invoke(Method.java:498)
13.09 21:09:51 [Server] WARN at me.incomprehendable.dev.pwp.transparentlisteners.PerWorldPluginLoader$1.execute(PerWorldPluginLoader.java:116)
13.09 21:09:51 [Server] WARN at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
13.09 21:09:51 [Server] WARN at me.incomprehendable.dev.pwp.transparentlisteners.PWPRegisteredListener.callEvent(PWPRegisteredListener.java:28)
13.09 21:09:51 [Server] WARN at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
13.09 21:09:51 [Server] WARN at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
13.09 21:09:51 [Server] WARN at net.minecraft.server.v1_10_R1.PlayerList.moveToWorld(PlayerList.java:686)
13.09 21:09:51 [Server] WARN at org.bukkit.craftbukkit.v1_10_R1.entity.CraftPlayer.teleport(CraftPlayer.java:471)
13.09 21:09:51 [Server] WARN at com.earth2me.essentials.Teleport.now(Teleport.java:126)
13.09 21:09:51 [Server] WARN at com.earth2me.essentials.Teleport.teleport(Teleport.java:194)
13.09 21:09:51 [Server] WARN at com.earth2me.essentials.Teleport.warp(Teleport.java:263)
13.09 21:09:51 [Server] WARN at com.earth2me.essentials.commands.Commandwarp.warpUser(Commandwarp.java:130)
13.09 21:09:51 [Server] WARN at com.earth2me.essentials.commands.Commandwarp.run(Commandwarp.java:51)
13.09 21:09:51 [Server] WARN at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:180)
13.09 21:09:51 [Server] WARN at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:527)
13.09 21:09:51 [Server] WARN at com.earth2me.essentials.Essentials.onCommand(Essentials.java:402)
13.09 21:09:51 [Server] WARN at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
13.09 21:09:51 [Server] WARN at me.incomprehendable.dev.pwp.FakeSimpleCommandMap.dispatch(FakeSimpleCommandMap.java:98)
13.09 21:09:51 [Server] WARN at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:646)
13.09 21:09:51 [Server] WARN at net.minecraft.server.v1_10_R1.PlayerConnection.handleCommand(PlayerConnection.java:1348)
13.09 21:09:51 [Server] WARN at net.minecraft.server.v1_10_R1.PlayerConnection.chat(PlayerConnection.java:1264)
13.09 21:09:51 [Server] WARN at org.bukkit.craftbukkit.v1_10_R1.entity.CraftPlayer.chat(CraftPlayer.java:238)
13.09 21:09:51 [Server] WARN at com.gmail.filoghost.chestcommands.internal.icon.command.PlayerIconCommand.execute(PlayerIconCommand.java:15)
13.09 21:09:51 [Server] WARN at com.gmail.filoghost.chestcommands.internal.CommandsClickHandler.onClick(CommandsClickHandler.java:34)
13.09 21:09:51 [Server] WARN at com.gmail.filoghost.chestcommands.api.Icon.onClick(Icon.java:319)
13.09 21:09:51 [Server] WARN at com.gmail.filoghost.chestcommands.internal.icon.ExtendedIcon.onClick(ExtendedIcon.java:243)
13.09 21:09:51 [Server] WARN at com.gmail.filoghost.chestcommands.task.ExecuteCommandsTask.run(ExecuteCommandsTask.java:21)
13.09 21:09:51 [Server] WARN at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71)
13.09 21:09:51 [Server] WARN at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
13.09 21:09:51 [Server] WARN at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:741)
13.09 21:09:51 [Server] WARN at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:399)
13.09 21:09:51 [Server] WARN at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:672)
13.09 21:09:51 [Server] WARN at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:571)
13.09 21:09:51 [Server] WARN at java.lang.Thread.run(Thread.java:745)
13.09 21:09:51 [Server] WARN [Multiverse-Inventories] Could not parse item: ItemStack{DIAMOND_BOOTS x 1, UNSPECIFIC_META:{meta-type=UNSPECIFIC, lore=[Stomp V], enchants={Custom Enchantment=0}}}
13.09 21:09:51 [Server] WARN [Multiverse-Inventories] Invalid key: 37 while parsing inventory
13.09 21:09:51 [Server] WARN [Multiverse-Inventories] Invalid key: 38 while parsing inventory
13.09 21:09:51 [Server] WARN [Multiverse-Inventories] Invalid key: 39 while parsing inventory

Can you help? 
Thanks

**Comment by GenerationMC** [comment]
Oh and per world inventories does not work at all not even a little bit. I've tried a few others too and they do not work either, this is the only decent one. Please consider supporting this again or letting someone else pick it up. I would even pay for it, it's the only thing that works for us single server owners.
