### ISSUE TITLE
Inventories dont Save

### ISSUE THREAD

**Issue by jacob99200** [Multiverse/Multiverse-Inventories#303]
I get this error when ever i change worlds, inventory rules dont apply becuase of this error

[17:28:52] [Server thread/ERROR]: Could not pass event PlayerChangedWorldEvent to Multiverse-Inventories v2.5-b335
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-f950f8e-58bff62]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-f950f8e-58bff62]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-f950f8e-58bff62]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-f950f8e-58bff62]
	at net.minecraft.server.v1_11_R1.PlayerList.moveToWorld(PlayerList.java:689) [spigot.jar:git-Spigot-f950f8e-58bff62]
	at org.bukkit.craftbukkit.v1_11_R1.entity.CraftPlayer.teleport(CraftPlayer.java:506) [spigot.jar:git-Spigot-f950f8e-58bff62]
	at org.bukkit.craftbukkit.v1_11_R1.entity.CraftEntity.teleport(CraftEntity.java:248) [spigot.jar:git-Spigot-f950f8e-58bff62]
	at com.onarandombox.MultiverseCore.utils.SimpleSafeTTeleporter.safelyTeleport(SimpleSafeTTeleporter.java:215) [Multiverse-Core-2.5.0-SNAPSHOT.jar:?]
	at com.onarandombox.MultiversePortals.listeners.PlayerListenerHelper.performTeleport(PlayerListenerHelper.java:44) [Multiverse-Portals-2.5.0-SNAPSHOT.jar:?]
	at com.onarandombox.MultiversePortals.listeners.MVPPlayerMoveListener.playerMove(MVPPlayerMoveListener.java:137) [Multiverse-Portals-2.5.0-SNAPSHOT.jar:?]
	at sun.reflect.GeneratedMethodAccessor22.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_111]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) [spigot.jar:git-Spigot-f950f8e-58bff62]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot.jar:git-Spigot-f950f8e-58bff62]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-f950f8e-58bff62]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-f950f8e-58bff62]
	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:609) [spigot.jar:git-Spigot-f950f8e-58bff62]
	at net.minecraft.server.v1_11_R1.PacketPlayInFlying.a(SourceFile:126) [spigot.jar:git-Spigot-f950f8e-58bff62]
	at net.minecraft.server.v1_11_R1.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:57) [spigot.jar:git-Spigot-f950f8e-58bff62]
	at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-f950f8e-58bff62]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_111]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_111]
	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [spigot.jar:git-Spigot-f950f8e-58bff62]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot.jar:git-Spigot-f950f8e-58bff62]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot.jar:git-Spigot-f950f8e-58bff62]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigot.jar:git-Spigot-f950f8e-58bff62]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot.jar:git-Spigot-f950f8e-58bff62]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
Caused by: java.lang.NoSuchMethodError: org.bukkit.entity.Player.getHealth()I
	at com.onarandombox.multiverseinventories.api.share.Sharables$7.updateProfile(Sharables.java:163) ~[?:?]
	at com.onarandombox.multiverseinventories.ShareHandler.updateProfile(ShareHandler.java:114) ~[?:?]
	at com.onarandombox.multiverseinventories.ShareHandler.completeSharing(ShareHandler.java:86) ~[?:?]
	at com.onarandombox.multiverseinventories.ShareHandler.handleSharing(ShareHandler.java:60) ~[?:?]
	at com.onarandombox.multiverseinventories.InventoriesListener.playerChangedWorld(InventoriesListener.java:189) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_111]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot.jar:git-Spigot-f950f8e-58bff62]
	... 28 more

**Comment by dumptruckman** [comment]
This should be resolved in latest dev builds.
