### ISSUE TITLE
Inventories not loading on 1.14.3

### ISSUE THREAD

**Issue by Bren00x** [Multiverse/Multiverse-Inventories#331]
Installed plugin and got this issue.
```[23:01:16 WARN]: Plugin Multiverse-Inventories v2.5.0-SNAPSHOT-b444 does not specify an api-version.
[23:01:16 ERROR]: Could not load 'plugins/Multiverse-Inventories-2.5.0-SNAPSHOT.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: com/pneumaticraft/commandhandler/multiverse/Command
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:138) ~[patched_1.14.3.jar:git-Paper-122]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:336) ~[patched_1.14.3.jar:git-Paper-122]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:256) ~[patched_1.14.3.jar:git-Paper-122]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.loadPlugins(CraftServer.java:354) ~[patched_1.14.3.jar:git-Paper-122]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.reload(CraftServer.java:855) ~[patched_1.14.3.jar:git-Paper-122]
	at org.bukkit.Bukkit.reload(Bukkit.java:610) ~[patched_1.14.3.jar:git-Paper-122]
	at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:54) ~[patched_1.14.3.jar:git-Paper-122]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.14.3.jar:git-Paper-122]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:738) ~[patched_1.14.3.jar:git-Paper-122]
	at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1831) ~[patched_1.14.3.jar:git-Paper-122]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1639) ~[patched_1.14.3.jar:git-Paper-122]
	at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.14.3.jar:git-Paper-122]
	at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.14.3.jar:git-Paper-122]
	at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:18) ~[patched_1.14.3.jar:git-Paper-122]
	at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.3.jar:git-Paper-122]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:127) ~[patched_1.14.3.jar:git-Paper-122]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.3.jar:git-Paper-122]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:105) ~[patched_1.14.3.jar:git-Paper-122]
	at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:1002) ~[patched_1.14.3.jar:git-Paper-122]
	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:995) ~[patched_1.14.3.jar:git-Paper-122]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:115) ~[patched_1.14.3.jar:git-Paper-122]
	at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:979) ~[patched_1.14.3.jar:git-Paper-122]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:912) ~[patched_1.14.3.jar:git-Paper-122]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NoClassDefFoundError: com/pneumaticraft/commandhandler/multiverse/Command
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:398) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:63) ~[patched_1.14.3.jar:git-Paper-122]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:134) ~[patched_1.14.3.jar:git-Paper-122]
	... 23 more
Caused by: java.lang.ClassNotFoundException: com.pneumaticraft.commandhandler.multiverse.Command
	at java.net.URLClassLoader.findClass(URLClassLoader.java:471) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:139) ~[patched_1.14.3.jar:git-Paper-122]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:85) ~[patched_1.14.3.jar:git-Paper-122]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:398) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:63) ~[patched_1.14.3.jar:git-Paper-122]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:134) ~[patched_1.14.3.jar:git-Paper-122]
	... 23 more```

**Comment by VaneHD** [comment]
multiverse-inventories does not support 1.14.

**Comment by EbonJaeger** [comment]
The latest version of it should work, if I remember correctly. You can get it from here: https://ci.onarandombox.com/view/Multiverse/job/Multiverse-Inventories/

**Comment by dumptruckman** [comment]
You must also have Multiverse-Core installed.
