### ISSUE TITLE
Multiverse-Inventories clears players inventory when changing worlds "too fast"

### ISSUE THREAD

**Issue by johananderssonv** [Multiverse/Multiverse-Inventories#382]
Hi! I have an issue where player inventories gets cleared once they leave MobArena. I opened a ticket on their page and this is their response.

@garbagemule:
The issue is not with MobArena, but with the plugin handling multiple inventories. You can solve the issue by configuring your multi-inventory plugin such that it either synchronously loads inventories early in the event cycle (PerWorldInventory works fine in that regard) or doesn't swap inventories at all. MobArena does exactly what it is supposed to: it stores and then clears your inventory when you join, and it clears and then restores your inventory when you leave. The problem is that the plugin handling inventories arrives at the party too late.

So the question is; is there anyway to configure the delay for when mvinv loads the players inventories when switching worlds?

**Comment by johananderssonv** [comment]
I've tried using version 3.0.0 and just tried it with version 4.0.0 snapshot

**Comment by garbagemule** [comment]
I just want to chime in here with a bit of technical details in hopes of clearing up any questions that may crop up :)

When a player joins an arena by clicking a join sign or typing the join command, MobArena executes a series of steps in a very specific order (see below) to accommodate various state changes made by other plugins, but it is a same-tick procedure, so any async operations initiated from the events triggered by these steps will likely run "too late" for MobArena to pick them up. The order of (relevant) steps is the following:

1. Teleport to arena lobby (a location in the arena).
2. Change gamemode to survival.
3. Store and then clear inventory.
4. Store and then set various player properties (flying, health, hunger, experience).

When the player leaves the arena, those steps are "undone" in the reverse order, i.e.:

1. Restore various player properties.
2. Clear inventory and restore saved inventory.
3. Restore gamemode.
4. Teleport the player back to where they joined.

We had a bit of an issue with PerWorldInventory loading inventories asynchronously, causing MobArena to store and clear the "wrong" inventory in step 3. PWI would load the world-specific inventory _after_ MobArena had already stored and cleared whatever was visible at the time of teleportation. Synchronous inventory loading seemed to be the solution over there.

I don't think this is a matter of inventories being wiped when players _leave_ MobArena, but rather when they _join_, but I could be wrong. Because MobArena does the inventory juggling before any gamemode or world changes happen, I don't see it being an on-leave issue, because I don't assume Multiverse-Inventories would kick in until the time of teleportation.

I also don't see a sound solution to this from the MobArena side of things. We could add delays here and there, but it's brittle, and I don't think that's the right way to go about it. We could make the join/leave process asynchronous and then depend on some sort of event, but I'm not a fan of introducing arbitrary dependencies for the sake of workarounds.

Hope that helps!

Cheers,
mule

**Comment by Skellett1** [comment]
I had a similar issue with inventories overwriting others, might be part of the same origin, as in your case the first inventory is being cleared before transferring back to the other world. 
Details for my case:
We're trying to reduce player health to half a heart utilizing AttributeModifiers on items, in our case golden boots. 
They're unbreakable and have the enchants curse of vanishing/binding. The modifier is limited to when they're worn on the feet. All of these attributes are hidden. 

Nothing goes wrong when the user has these in any slot where they have no effect however if they're worn as intended and the player moves to a world which does not share the inventory, first the inventory gets cleared and then the inventory from the world with the boots is transferred over, this includes the ender chest. 
It seems to be somewhat flashy, you're actually able to see for a split second, that your inventory is empty before you then have the items which you should not have.

**Comment by Skellett1** [comment]
I also just found this in the console:

[23:37:05 ERROR]: Could not pass event PlayerChangedWorldEvent to Multiverse-Inventories v4.0.0-SNAPSHOT-bUNKNOWN
java.lang.IllegalArgumentException: Health must be between 0 and 1.0, but was 20.0. (attribute base value: 20.0, player: Skellett1)
        at org.bukkit.craftbukkit.v1_16_R1.entity.CraftLivingEntity.setHealth(CraftLivingEntity.java:115) ~[patched_1.16.1.jar:git-Paper-49]
        at com.onarandombox.multiverseinventories.share.Sharables$5.updatePlayer(Sharables.java:183) ~[?:?]
        at com.onarandombox.multiverseinventories.ShareHandler.updatePlayer(ShareHandler.java:139) ~[?:?]
        at com.onarandombox.multiverseinventories.ShareHandler.completeSharing(ShareHandler.java:88) ~[?:?]
        at com.onarandombox.multiverseinventories.ShareHandler.handleSharing(ShareHandler.java:59) ~[?:?]
        at com.onarandombox.multiverseinventories.InventoriesListener.playerChangedWorld(InventoriesListener.java:209) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor107.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.1.jar:git-Paper-49]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.1.jar:git-Paper-49]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.1.jar:git-Paper-49]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.1.jar:git-Paper-49]
        at net.minecraft.server.v1_16_R1.PlayerList.moveToWorld(PlayerList.java:869) ~[patched_1.16.1.jar:git-Paper-49]
        at org.bukkit.craftbukkit.v1_16_R1.entity.CraftPlayer.teleport(CraftPlayer.java:813) ~[patched_1.16.1.jar:git-Paper-49]
        at org.bukkit.entity.Entity.lambda$teleportAsync$0(Entity.java:178) ~[patched_1.16.1.jar:git-Paper-49]
        at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670) ~[?:1.8.0_252]
        at java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:683) ~[?:1.8.0_252]
        at java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2010) ~[?:1.8.0_252]
        at org.bukkit.entity.Entity.teleportAsync(Entity.java:178) ~[patched_1.16.1.jar:git-Paper-49]
        at org.bukkit.craftbukkit.v1_16_R1.entity.CraftPlayer.teleportAsync(CraftPlayer.java:751) ~[patched_1.16.1.jar:git-Paper-49]
        at com.earth2me.essentials.paperlib.features.asyncteleport.AsyncTeleportPaper_13.teleportAsync(AsyncTeleportPaper_13.java:13) ~[?:?]
        at com.earth2me.essentials.paperlib.environments.Environment.teleport(Environment.java:92) ~[?:?]
        at com.earth2me.essentials.paperlib.PaperLib.teleportAsync(PaperLib.java:87) ~[?:?]
        at com.earth2me.essentials.AsyncTeleport.lambda$nowAsync$3(AsyncTeleport.java:211) ~[?:?]
        at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670) ~[?:1.8.0_252]
        at java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:683) ~[?:1.8.0_252]
        at java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2010) ~[?:1.8.0_252]
        at com.earth2me.essentials.AsyncTeleport.nowAsync(AsyncTeleport.java:182) ~[?:?]
        at com.earth2me.essentials.AsyncTeleport.teleport(AsyncTeleport.java:278) ~[?:?]
        at com.earth2me.essentials.AsyncTeleport.warp(AsyncTeleport.java:416) ~[?:?]
        at com.earth2me.essentials.commands.Commandwarp.warpUser(Commandwarp.java:100) ~[?:?]
        at com.earth2me.essentials.commands.Commandwarp.run(Commandwarp.java:47) ~[?:?]
        at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:168) ~[?:?]
        at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:615) ~[?:?]
        at com.earth2me.essentials.Essentials.onCommand(Essentials.java:525) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.1.jar:git-Paper-49]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.1.jar:git-Paper-49]
        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchCommand(CraftServer.java:794) ~[patched_1.16.1.jar:git-Paper-49]
        at net.minecraft.server.v1_16_R1.PlayerConnection.handleCommand(PlayerConnection.java:1908) ~[patched_1.16.1.jar:git-Paper-49]
        at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1719) ~[patched_1.16.1.jar:git-Paper-49]
        at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.16.1.jar:git-Paper-49]
        at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.16.1.jar:git-Paper-49]
        at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.16.1.jar:git-Paper-49]
        at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18) ~[patched_1.16.1.jar:git-Paper-49]
        at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.1.jar:git-Paper-49]
        at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.1.jar:git-Paper-49]
        at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.1.jar:git-Paper-49]
        at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:1136) ~[patched_1.16.1.jar:git-Paper-49]
        at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:1129) ~[patched_1.16.1.jar:git-Paper-49]
        at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.1.jar:git-Paper-49]
        at net.minecraft.server.v1_16_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1090) ~[patched_1.16.1.jar:git-Paper-49]
        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1004) ~[patched_1.16.1.jar:git-Paper-49]
        at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-49]

**Comment by IDzyre** [comment]
If you have a lobby world that you spawn in, and you have a survival world, and a nether world linked, if you disconnect or go to the lobby world, and go through a multiverse portal to the survival world (with last_location on) it will not sync your inventory with the survival world, it will sync it to the lobby world, even if the survival world and the nether world have inventory shared.

**Comment by benwoo1110** [comment]
@IDzyre doesn't look like your issues is related to this, so please create a new issue and follow the issue template.
