### ISSUE TITLE
Error with HP amount on PlayerChangedWorldEvent

### ISSUE THREAD

**Issue by Darwin1546** [Multiverse/Multiverse-Inventories#385]
With HP set by mmocore, i got this exception:

```
[00:42:31 ERROR]: Could not pass event PlayerChangedWorldEvent to Multiverse-Inventories v3.0.0-b459
java.lang.IllegalArgumentException: Health must be between 0 and 11.199999809265137, but was 20.0. (attribute base value: 20.0, player: Darwinian)
        at org.bukkit.craftbukkit.v1_14_R1.entity.CraftLivingEntity.setHealth(CraftLivingEntity.java:111) ~[patched_1.14.4.jar:git-Paper-243]
        at com.onarandombox.multiverseinventories.share.Sharables$5.updatePlayer(Sharables.java:167) ~[?:?]
        at com.onarandombox.multiverseinventories.ShareHandler.updatePlayer(ShareHandler.java:139) ~[?:?]
        at com.onarandombox.multiverseinventories.ShareHandler.completeSharing(ShareHandler.java:88) ~[?:?]
        at com.onarandombox.multiverseinventories.ShareHandler.handleSharing(ShareHandler.java:59) ~[?:?]
        at com.onarandombox.multiverseinventories.InventoriesListener.playerChangedWorld(InventoriesListener.java:209) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor291.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.4.jar:git-Paper-243]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.4.jar:git-Paper-243]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.4.jar:git-Paper-243]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.4.jar:git-Paper-243]
        at net.minecraft.server.v1_14_R1.PlayerList.moveToWorld(PlayerList.java:739) ~[patched_1.14.4.jar:git-Paper-243]
        at org.bukkit.craftbukkit.v1_14_R1.entity.CraftPlayer.teleport(CraftPlayer.java:792) ~[patched_1.14.4.jar:git-Paper-243]
        at org.bukkit.craftbukkit.v1_14_R1.entity.CraftEntity.teleport(CraftEntity.java:489) ~[patched_1.14.4.jar:git-Paper-243]
        at com.onarandombox.MultiverseCore.utils.SimpleSafeTTeleporter.safelyTeleport(SimpleSafeTTeleporter.java:215) ~[?:?]
        at com.onarandombox.MultiverseCore.utils.SimpleSafeTTeleporter.teleport(SimpleSafeTTeleporter.java:335) ~[?:?]
        at com.onarandombox.MultiverseCore.commands.TeleportCommand.runCommand(TeleportCommand.java:163) ~[?:?]
        at com.onarandombox.commandhandler.CommandHandler.checkAndRunCommand(CommandHandler.java:296) ~[?:?]
        at com.onarandombox.commandhandler.CommandHandler.processFoundCommands(CommandHandler.java:143) ~[?:?]
        at com.onarandombox.commandhandler.CommandHandler.locateAndRunCommand(CommandHandler.java:93) ~[?:?]
        at com.onarandombox.MultiverseCore.MultiverseCore.onCommand(MultiverseCore.java:910) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.14.4.jar:git-Paper-243]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.14.4.jar:git-Paper-243]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:739) ~[patched_1.14.4.jar:git-Paper-243]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchServerCommand(CraftServer.java:701) ~[patched_1.14.4.jar:git-Paper-243]
        at net.minecraft.server.v1_14_R1.DedicatedServer.handleCommandQueue(DedicatedServer.java:456) ~[patched_1.14.4.jar:git-Paper-243]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:418) ~[patched_1.14.4.jar:git-Paper-243]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1098) ~[patched_1.14.4.jar:git-Paper-243]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:925) ~[patched_1.14.4.jar:git-Paper-243]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]
```

**Comment by benwoo1110** [comment]
similar to #383
