### ISSUE TITLE
Player generated files do not need to successfully enter the server

### ISSUE THREAD

**Issue by From-pErfo** [Multiverse/Multiverse-Inventories#494]
The whitelist is enabled on my server, but players blocked by the whitelist will generate files in the `/plugins/Multiverse-Inventories/players` directory
I have tried the whitelist plugin and the built-in whitelist function, these files will still be generated

Is this a bug?
A lot of these files are generated when my server is stress tested by fake players

**Comment by benwoo1110** [comment]
Is the whitelist by minecraft or a custom plugin?

**Comment by From-pErfo** [comment]
> 是我的世界的白名单还是自定义插件？

I tried these two

**Comment by From-pErfo** [comment]
> so you will need to provide more information as requested in the issue template.

Sorry I overlooked the issue template, I'll add it here

**Server version:**
`This server is running Purpur version git-Purpur-1428 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 9beb23b on ver/1.17.1)`

**Full output of `/mv version -p`:**
```mv version -p
[20:09:49 INFO]: [Multiverse-Core] Multiverse-Core Version: 4.3.1-b861
[20:09:49 INFO]: [Multiverse-Core] Bukkit Version: git-Purpur-1428 (MC: 1.17.1)
[20:09:49 INFO]: [Multiverse-Core] Loaded Worlds: [{"MVWorld@1856108775":{"Gen":"null","Type":"NORMAL","Env":"THE_END","Name":"world_the_end"}}, {"MVWorld@2111853374":{"Gen":"null","Type":"NORMAL","Env":"NORMAL","Name":"world"}}, {"MVWorld@1267836661":{"Gen":"null","Type":"NORMAL","Env":"NETHER","Name":"world_nether"}}]
[20:09:49 INFO]: [Multiverse-Core] Multiverse Plugins Loaded: 2
[20:09:49 INFO]: [Multiverse-Core] Economy being used: Simple Item Economy
[20:09:49 INFO]: [Multiverse-Core] Permissions Plugin: Bukkit Permissions (SuperPerms)
[20:09:49 INFO]: [Multiverse-Core] Dumping Config Values: (version 2.9)
[20:09:49 INFO]: [Multiverse-Core]   enforceaccess: false
[20:09:49 INFO]: [Multiverse-Core]   prefixchat: false
[20:09:49 INFO]: [Multiverse-Core]   prefixchatformat: [%world%]%chat%
[20:09:49 INFO]: [Multiverse-Core]   useasyncchat: true
[20:09:49 INFO]: [Multiverse-Core]   teleportintercept: true
[20:09:49 INFO]: [Multiverse-Core]   firstspawnoverride: true
[20:09:49 INFO]: [Multiverse-Core]   displaypermerrors: true
[20:09:49 INFO]: [Multiverse-Core]   enablebuscript: true
[20:09:49 INFO]: [Multiverse-Core]   globaldebug: 0
[20:09:49 INFO]: [Multiverse-Core]   silentstart: false
[20:09:49 INFO]: [Multiverse-Core]   messagecooldown: 5000
[20:09:49 INFO]: [Multiverse-Core]   version: 2.9
[20:09:49 INFO]: [Multiverse-Core]   firstspawnworld: world
[20:09:49 INFO]: [Multiverse-Core]   teleportcooldown: 1000
[20:09:49 INFO]: [Multiverse-Core]   defaultportalsearch: true
[20:09:49 INFO]: [Multiverse-Core]   portalsearchradius: 128
[20:09:49 INFO]: [Multiverse-Core]   autopurge: true
[20:09:49 INFO]: [Multiverse-Core] Special Code: FRN002
[20:09:49 INFO]: [Multiverse-NetherPortals] Multiverse-NetherPortals Version: 4.2.1-b786
[20:09:49 INFO]: [Multiverse-NetherPortals] Nether Prefix:
[20:09:49 INFO]: [Multiverse-NetherPortals] Nether Suffix: _nether
[20:09:49 INFO]: [Multiverse-NetherPortals] End Prefix:
[20:09:49 INFO]: [Multiverse-NetherPortals] End Suffix: _the_end
[20:09:49 INFO]: [Multiverse-NetherPortals] Nether Links: {}
[20:09:49 INFO]: [Multiverse-NetherPortals] End Links: {}
[20:09:49 INFO]: [Multiverse-NetherPortals] Bounceback: false
[20:09:49 INFO]: [Multiverse-NetherPortals] Teleport Entities: true
[20:09:49 INFO]: [Multiverse-NetherPortals] Send Disabled Portal Message: false
[20:09:49 INFO]: [Multiverse-NetherPortals] Send No Destination Message: false
[20:09:49 INFO]: [Multiverse-NetherPortals] Special Code: FRN001
[20:09:49 INFO]: [Multiverse-Inventories] Multiverse-Inventories Version: 4.2.2-b500
[20:09:49 INFO]: [Multiverse-Inventories] === Settings ===
[20:09:49 INFO]: [Multiverse-Inventories] First Run: false
[20:09:49 INFO]: [Multiverse-Inventories] Using Bypass: false
[20:09:49 INFO]: [Multiverse-Inventories] Default Ungrouped Worlds: false
[20:09:49 INFO]: [Multiverse-Inventories] Save and Load on Log In and Out: false
[20:09:49 INFO]: [Multiverse-Inventories] Using GameMode Profiles: false
[20:09:49 INFO]: [Multiverse-Inventories] === Shares ===
[20:09:49 INFO]: [Multiverse-Inventories] Optionals for Ungrouped Worlds: true
[20:09:49 INFO]: [Multiverse-Inventories] Enabled Optionals:
[20:09:49 INFO]: [Multiverse-Inventories] === Groups ===
[20:09:49 INFO]: [Multiverse-Inventories] default: {Worlds: [world, world_the_end, world_nether], Shares: [hit_points, economy, food_level, saturation, exhaustion, xp, total_xp, lvl, inventory_contents, armor_contents, bed_spawn, maximum_air, remaining_air, fall_distance, fire_ticks, potion_effects, last_location, ender_chest, off_hand]}
[20:09:51 WARN]: java.io.IOException: Server returned HTTP response code: 400 for URL: https://api-ssl.bitly.com/v4/shorten
[20:09:51 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1997)
[20:09:51 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
[20:09:51 WARN]:        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
[20:09:51 WARN]:        at Multiverse-Core-4.3.1.jar//com.onarandombox.MultiverseCore.utils.webpaste.HttpAPIClient.exec(HttpAPIClient.java:109)
[20:09:51 WARN]:        at Multiverse-Core-4.3.1.jar//com.onarandombox.MultiverseCore.utils.webpaste.BitlyURLShortener.shorten(BitlyURLShortener.java:49)
[20:09:51 WARN]:        at Multiverse-Core-4.3.1.jar//com.onarandombox.MultiverseCore.commands.VersionCommand.postToService(VersionCommand.java:211)
[20:09:51 WARN]:        at Multiverse-Core-4.3.1.jar//com.onarandombox.MultiverseCore.commands.VersionCommand.access$000(VersionCommand.java:36)
[20:09:51 WARN]:        at Multiverse-Core-4.3.1.jar//com.onarandombox.MultiverseCore.commands.VersionCommand$1.run(VersionCommand.java:174)
[20:09:51 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101)
[20:09:51 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[20:09:51 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[20:09:51 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[20:09:51 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[20:09:51 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[20:09:51 INFO]: [Multiverse-Core] Version info dumped here: https://paste.gg/0fd8bb6f72b74e2c8c2c10abede8fe6f
```

**Server log:**
No output other than whitelist
