### ISSUE TITLE
Сервер вылетает при телепортации в мир.

### ISSUE THREAD

**Issue by Vyacheslav73195** [Multiverse/Multiverse-Inventories#509]
Если игрок находится в мире выживания, и кликает по табличке с командой mvtp creative, держа в руках фейрверки, при этом у него пустой инвентарь в мире креатива, то сервер вылетает с ошибкой:

[21:11:19] [Server thread/INFO]: Vyacheslav73195 issued server command: /mvtp @s creative
[21:11:19] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.AssertionError: TRAP
	at net.minecraft.world.item.ItemStack.updateEmptyCacheFlag(ItemStack.java:247) ~[paper-1.19.2.jar:git-Paper-215]
	at net.minecraft.world.item.ItemStack.setCount(ItemStack.java:1278) ~[paper-1.19.2.jar:git-Paper-215]
	at net.minecraft.world.item.ItemStack.grow(ItemStack.java:1282) ~[paper-1.19.2.jar:git-Paper-215]
	at net.minecraft.world.item.ItemStack.shrink(ItemStack.java:1286) ~[paper-1.19.2.jar:git-Paper-215]
	at net.minecraft.world.item.FireworkRocketItem.useOn(FireworkRocketItem.java:52) ~[?:?]
	at net.minecraft.world.item.ItemStack.useOn(ItemStack.java:348) ~[paper-1.19.2.jar:git-Paper-215]
	at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:588) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1969) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:37) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.a(ServerboundUseItemOnPacket.java:9) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.2.jar:git-Paper-215]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1341) ~[paper-1.19.2.jar:git-Paper-215]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185) ~[paper-1.19.2.jar:git-Paper-215]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1318) ~[paper-1.19.2.jar:git-Paper-215]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1311) ~[paper-1.19.2.jar:git-Paper-215]
	at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1445) ~[paper-1.19.2.jar:git-Paper-215]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.2.jar:git-Paper-215]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-215]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
	
	Пояснения: Есть миры креатива и выживания, инвентарь в которых раздельный.
	"Табличка с командами" это https://minecraft.tools/en/sign.php
	Если что-то не понятно, готов пояснить.
	
	Инфа по серверу:
	Paper 1.19.2
	Плагины:
	ArmorStandTools, AuthMe, BetterSleeping3, Choptree2.1, ConsoleSpamFix, CoreProtect, crafts, CreativeManager, CustomDiscs, dynmap, Dynmap-WorldGuard, EasyWhitelist*, emotecraft, Essentials, EssentialsSelectors, FastAsyncWorldEdit (WorldEdit), GSit, lightblockcraft, LuckPerms, Matrix, Multiverse-Core, Multiverse-Inventories, MyCommand, NoChatReports, NuclearMC, OpenInv, PL-Hide, PlaceholderAPI, ProtocolLib, SpigotDash, SuperVanish, TAB, thunderbow, tntbow*, Vault, voicechat, WorldBorder, WorldGuard

**Comment by zax71** [comment]
We do not support offline mode servers (see AuthMe in plugins)
