### ISSUE TITLE
Can't load the plugin

### ISSUE THREAD

**Issue by Kewuaipao** [Multiverse/Multiverse-Inventories#511]
paper 1.18.2
```
[01:48:38 INFO]: [Multiverse-Inventories] Enabling Multiverse-Inventories v4.2.3-b523
[01:48:38 ERROR]: [Multiverse-Inventories] Error while trying to load localization for the given Locale!
[01:48:38 INFO]: [Multiverse-Inventories] Disabling Multiverse-Inventories v4.2.3-b523
[01:48:38 ERROR]: Error occurred while disabling Multiverse-Inventories v4.2.3-b523 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "com.onarandombox.multiverseinventories.InventoriesDupingPatch.disable()" because "this.dupingPatch" is null
        at com.onarandombox.multiverseinventories.MultiverseInventories.onDisable(MultiverseInventories.java:115) ~[Multiverse-Inventories-4.2.3.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:399) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:578) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at com.onarandombox.multiverseinventories.MultiverseInventories.onEnable(MultiverseInventories.java:154) ~[Multiverse-Inventories-4.2.3.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:541) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:560) ~[paper-1.18.2.jar:git-Paper-387]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:474) ~[paper-1.18.2.jar:git-Paper-387]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:665) ~[paper-1.18.2.jar:git-Paper-387]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:432) ~[paper-1.18.2.jar:git-Paper-387]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:316) ~[paper-1.18.2.jar:git-Paper-387]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1164) ~[paper-1.18.2.jar:git-Paper-387]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.2.jar:git-Paper-387]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by Kewuaipao** [comment]
Sorry I edit the wrong setting(locale) in the config file..

**Comment by Kewuaipao** [comment]
Sorry I edit the wrong setting(locale) in the config file..
