### ISSUE TITLE
NPE on movement between worlds

### ISSUE THREAD

**Issue by SlimeDog** [Multiverse/Multiverse-Inventories#553]
### Information

* **Server version:** 
```
> version
[10:11:47 INFO]: This server is running Paper version 1.21.1-123-master@aebbdc9 (2024-10-16T14:15:18Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.21.1-122-4430e96 (MC: 1.21.1
```

* **Full output of `/mv version -p`:** 
```
> mv version
[10:11:10 INFO]: [Multiverse-Core] Multiverse-Core Version: 4.3.13-SNAPSHOT
[10:11:10 INFO]: [Multiverse-Core] Bukkit Version: 1.21.1-123-aebbdc9 (MC: 1.21.1)
[10:11:10 INFO]: [Multiverse-Core] Loaded Worlds: [{"MVWorld@879348111":{"Gen":"null","Type":"NORMAL","Env":"NORMAL","Name":"world_yellowdog"}}, {"MVWorld@807207316":{"Gen":"null","Type":"NORMAL","Env":"NORMAL","Name":"world_whitedog"}}, {"MVWorld@985882440":{"Gen":"BentoBox","Type":"NORMAL","Env":"THE_END","Name":"world_skyblock_the_end"}}, {"MVWorld@133893304":{"Gen":"null","Type":"NORMAL","Env":"NORMAL","Name":"world_westeros"}}, {"MVWorld@2099550329":{"Gen":"VoidGen","Type":"NORMAL","Env":"NORMAL","Name":"world_void"}}, {"MVWorld@636303336":{"Gen":"BentoBox","Type":"NORMAL","Env":"NETHER","Name":"world_skyblock_nether"}}, {"MVWorld@99882242":{"Gen":"BentoBox","Type":"NORMAL","Env":"NORMAL","Name":"world_skyblock"}}, {"MVWorld@1521829832":{"Gen":"null","Type":"NORMAL","Env":"NORMAL","Name":"world_luckyblock"}}, {"MVWorld@59501495":{"Gen":"null","Type":"NORMAL","Env":"THE_END","Name":"world_the_end"}}, {"MVWorld@1335217753":{"Gen":"null","Type":"NORMAL","Env":"NORMAL","Name":"world"}}, {"MVWorld@1785503404":{"Gen":"null","Type":"NORMAL","Env":"NETHER","Name":"world_nether"}}, {"MVWorld@327522258":{"Gen":"null","Type":"NORMAL","Env":"NORMAL","Name":"world_lobby"}}, {"MVWorld@446107438":{"Gen":"CityWorld","Type":"NORMAL","Env":"NORMAL","Name":"world_city"}}, {"MVWorld@258899246":{"Gen":"null","Type":"NORMAL","Env":"NORMAL","Name":"world_blackdog"}}]
[10:11:10 INFO]: [Multiverse-Core] Multiverse Plugins Loaded: 3
[10:11:10 INFO]: [Multiverse-Core] Economy being used: EssentialsX Economy
[10:11:10 INFO]: [Multiverse-Core] Permissions Plugin: Bukkit Permissions (SuperPerms)
[10:11:10 INFO]: [Multiverse-Core] Dumping Config Values: (version 2.9)
[10:11:10 INFO]: [Multiverse-Core]   enforceaccess: true
[10:11:10 INFO]: [Multiverse-Core]   prefixchat: false
[10:11:10 INFO]: [Multiverse-Core]   prefixchatformat: [%world%]%chat%
[10:11:10 INFO]: [Multiverse-Core]   useasyncchat: true
[10:11:10 INFO]: [Multiverse-Core]   teleportintercept: true
[10:11:10 INFO]: [Multiverse-Core]   firstspawnoverride: true
[10:11:10 INFO]: [Multiverse-Core]   displaypermerrors: true
[10:11:10 INFO]: [Multiverse-Core]   enablebuscript: false
[10:11:10 INFO]: [Multiverse-Core]   globaldebug: 0
[10:11:10 INFO]: [Multiverse-Core]   silentstart: false
[10:11:10 INFO]: [Multiverse-Core]   messagecooldown: 5000
[10:11:10 INFO]: [Multiverse-Core]   version: 2.9
[10:11:10 INFO]: [Multiverse-Core]   firstspawnworld: world
[10:11:10 INFO]: [Multiverse-Core]   teleportcooldown: 1000
[10:11:10 INFO]: [Multiverse-Core]   defaultportalsearch: true
[10:11:10 INFO]: [Multiverse-Core]   portalsearchradius: 128
[10:11:10 INFO]: [Multiverse-Core]   autopurge: true
[10:11:10 INFO]: [Multiverse-Core] Special Code: FRN002
[10:11:10 INFO]: [Multiverse-Portals] Multiverse-Portals Version: 4.3.0-SNAPSHOT
[10:11:10 INFO]: [Multiverse-Portals] Loaded Portals: 8
[10:11:10 INFO]: [Multiverse-Portals] Dumping Portal Values: (version 2.7)
[10:11:10 INFO]: [Multiverse-Portals]   wand: 271
[10:11:10 INFO]: [Multiverse-Portals]   useonmove: true
[10:11:10 INFO]: [Multiverse-Portals]   bucketfilling: true
[10:11:10 INFO]: [Multiverse-Portals]   portalsdefaulttonether: false
[10:11:10 INFO]: [Multiverse-Portals]   enforceportalaccess: false
[10:11:10 INFO]: [Multiverse-Portals]   portalcooldown: 1000
[10:11:10 INFO]: [Multiverse-Portals]   clearonremove: false
[10:11:10 INFO]: [Multiverse-Portals]   framematerials: []
[10:11:10 INFO]: [Multiverse-Portals] Special Code: FRN001
[10:11:10 INFO]: [Multiverse-Inventories] Multiverse-Inventories Version: 4.2.7-SNAPSHOT
[10:11:10 INFO]: [Multiverse-Inventories] === Settings ===
[10:11:10 INFO]: [Multiverse-Inventories] First Run: false
[10:11:10 INFO]: [Multiverse-Inventories] Using Bypass: false
[10:11:10 INFO]: [Multiverse-Inventories] Default Ungrouped Worlds: false
[10:11:10 INFO]: [Multiverse-Inventories] Save and Load on Log In and Out: false
[10:11:10 INFO]: [Multiverse-Inventories] Using GameMode Profiles: false
[10:11:10 INFO]: [Multiverse-Inventories] === Shares ===
[10:11:10 INFO]: [Multiverse-Inventories] Optionals for Ungrouped Worlds: true
[10:11:10 INFO]: [Multiverse-Inventories] Enabled Optionals: 
[10:11:10 INFO]: [Multiverse-Inventories] === Groups ===
[10:11:10 INFO]: [Multiverse-Inventories] blackdog: {Worlds: [world_blackdog_nether, world_blackdog_the_end, world_blackdog], Shares: [hit_points, economy, food_level, saturation, exhaustion, xp, total_xp, lvl, inventory_contents, armor_contents, bed_spawn, maximum_air, remaining_air, fall_distance, fire_ticks, potion_effects, last_location, ender_chest, off_hand]}
[10:11:10 INFO]: [Multiverse-Inventories] city: {Worlds: [world_city_the_end, world_city, world_city_nether], Shares: [hit_points, economy, food_level, saturation, exhaustion, xp, total_xp, lvl, inventory_contents, armor_contents, bed_spawn, maximum_air, remaining_air, fall_distance, fire_ticks, potion_effects, last_location, ender_chest, off_hand]}
[10:11:10 INFO]: [Multiverse-Inventories] creative: {Worlds: [world, world_the_end, world_nether], Shares: [hit_points, economy, food_level, saturation, exhaustion, xp, total_xp, lvl, inventory_contents, armor_contents, bed_spawn, maximum_air, remaining_air, fall_distance, fire_ticks, potion_effects, last_location, ender_chest, off_hand]}
[10:11:10 INFO]: [Multiverse-Inventories] lobby: {Worlds: [world_lobby], Shares: [hit_points, economy, food_level, saturation, exhaustion, xp, total_xp, lvl, inventory_contents, armor_contents, bed_spawn, maximum_air, remaining_air, fall_distance, fire_ticks, potion_effects, last_location, ender_chest, off_hand]}
[10:11:10 INFO]: [Multiverse-Inventories] luckyblock: {Worlds: [world_luckyblock], Shares: [hit_points, economy, food_level, saturation, exhaustion, xp, total_xp, lvl, inventory_contents, armor_contents, bed_spawn, maximum_air, remaining_air, fall_distance, fire_ticks, potion_effects, last_location, ender_chest, off_hand]}
[10:11:10 INFO]: [Multiverse-Inventories] mini: {Worlds: [world_minigames], Shares: [hit_points, economy, food_level, saturation, exhaustion, xp, total_xp, lvl, inventory_contents, armor_contents, bed_spawn, maximum_air, remaining_air, fall_distance, fire_ticks, potion_effects, last_location, ender_chest, off_hand]}
[10:11:10 INFO]: [Multiverse-Inventories] skyblock: {Worlds: [world_skyblock, world_skyblock_the_end, world_skyblock_nether], Shares: [hit_points, economy, food_level, saturation, exhaustion, xp, total_xp, lvl, inventory_contents, armor_contents, bed_spawn, maximum_air, remaining_air, fall_distance, fire_ticks, potion_effects, last_location, ender_chest, off_hand]}
[10:11:10 INFO]: [Multiverse-Inventories] void: {Worlds: [world_void], Shares: [hit_points, economy, food_level, saturation, exhaustion, xp, total_xp, lvl, inventory_contents, armor_contents, bed_spawn, maximum_air, remaining_air, fall_distance, fire_ticks, potion_effects, last_location, ender_chest, off_hand]}
[10:11:10 INFO]: [Multiverse-Inventories] westeros: {Worlds: [world_westeros], Shares: [hit_points, economy, food_level, saturation, exhaustion, xp, total_xp, lvl, inventory_contents, armor_contents, bed_spawn, maximum_air, remaining_air, fall_distance, fire_ticks, potion_effects, last_location, ender_chest, off_hand]}
[10:11:10 INFO]: [Multiverse-Inventories] whitedog: {Worlds: [world_whitedog_the_end, world_whitedog, world_whitedog_nether], Shares: [hit_points, economy, food_level, saturation, exhaustion, xp, total_xp, lvl, inventory_contents, armor_contents, bed_spawn, maximum_air, remaining_air, fall_distance, fire_ticks, potion_effects, last_location, ender_chest, off_hand]}
[10:11:10 INFO]: [Multiverse-Inventories] yellowdog: {Worlds: [world_yellowdog_the_end, world_yellowdog, world_yellowdog_nether], Shares: [hit_points, economy, food_level, saturation, exhaustion, xp, total_xp, lvl, inventory_contents, armor_contents, bed_spawn, maximum_air, remaining_air, fall_distance, fire_ticks, potion_effects, last_location, ender_chest, off_hand]}
[10:11:10 INFO]: [Multiverse-NetherPortals] Multiverse-NetherPortals Version: 4.3.0-SNAPSHOT
[10:11:10 INFO]: [Multiverse-NetherPortals] Nether Prefix: 
[10:11:10 INFO]: [Multiverse-NetherPortals] Nether Suffix: _nether
[10:11:10 INFO]: [Multiverse-NetherPortals] End Prefix: 
[10:11:10 INFO]: [Multiverse-NetherPortals] End Suffix: _the_end
[10:11:10 INFO]: [Multiverse-NetherPortals] Nether Links: {}
[10:11:10 INFO]: [Multiverse-NetherPortals] End Links: {}
[10:11:10 INFO]: [Multiverse-NetherPortals] Bounceback: true
[10:11:10 INFO]: [Multiverse-NetherPortals] Teleport Entities: true
[10:11:10 INFO]: [Multiverse-NetherPortals] Send Disabled Portal Message: true
[10:11:10 INFO]: [Multiverse-NetherPortals] Send No Destination Message: true
[10:11:10 INFO]: [Multiverse-NetherPortals] Server Allow Nether: true
[10:11:10 INFO]: [Multiverse-NetherPortals] Server Allow End: true
[10:11:10 INFO]: [Multiverse-NetherPortals] Special Code: FRN001
```

* **ERROR from Server log:** 
```
[10:04:34 ERROR]: [org.bukkit.configuration.serialization.ConfigurationSerialization] Could not call method 'public static org.bukkit.inventory.meta.ItemMeta org.bukkit.craftbukkit.inventory.SerializableMeta.deserialize(java.util.Map) throws java.lang.Throwable' of class org.bukkit.craftbukkit.inventory.SerializableMeta for deserialization
java.lang.NullPointerException: null
        at java.base/java.util.Objects.requireNonNull(Objects.java:220) ~[?:?]
        at org.bukkit.craftbukkit.inventory.CraftMetaBlockState.getBlockState(CraftMetaBlockState.java:280) ~[paper-1.21.1.jar:1.21.1-123-aebbdc9]
        at org.bukkit.craftbukkit.inventory.SerializableMeta.deserialize(SerializableMeta.java:80) ~[paper-1.21.1.jar:1.21.1-123-aebbdc9]
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
        at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
        at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeViaMethod(ConfigurationSerialization.java:87) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.configuration.serialization.ConfigurationSerialization.deserialize(ConfigurationSerialization.java:129) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeObject(ConfigurationSerialization.java:209) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at Multiverse-Inventories-4.2.7-pre.jar/com.onarandombox.multiverseinventories.utils.configuration.util.SerializationHelper.deserialize(SerializationHelper.java:125) ~[Multiverse-Inventories-4.2.7-pre.jar:?]
        at Multiverse-Inventories-4.2.7-pre.jar/com.onarandombox.multiverseinventories.utils.configuration.util.SerializationHelper.deserialize(SerializationHelper.java:116) ~[Multiverse-Inventories-4.2.7-pre.jar:?]
        at Multiverse-Inventories-4.2.7-pre.jar/com.onarandombox.multiverseinventories.utils.configuration.util.SerializationHelper.deserialize(SerializationHelper.java:116) ~[Multiverse-Inventories-4.2.7-pre.jar:?]
        at Multiverse-Inventories-4.2.7-pre.jar/com.onarandombox.multiverseinventories.utils.configuration.util.SerializationHelper.deserialize(SerializationHelper.java:116) ~[Multiverse-Inventories-4.2.7-pre.jar:?]
        at Multiverse-Inventories-4.2.7-pre.jar/com.onarandombox.multiverseinventories.utils.configuration.util.SerializationHelper.deserialize(SerializationHelper.java:116) ~[Multiverse-Inventories-4.2.7-pre.jar:?]
        at Multiverse-Inventories-4.2.7-pre.jar/com.onarandombox.multiverseinventories.utils.configuration.json.JsonConfiguration.convertMapsToSections(JsonConfiguration.java:75) ~[Multiverse-Inventories-4.2.7-pre.jar:?]
        at Multiverse-Inventories-4.2.7-pre.jar/com.onarandombox.multiverseinventories.utils.configuration.json.JsonConfiguration.loadFromString(JsonConfiguration.java:68) ~[Multiverse-Inventories-4.2.7-pre.jar:?]
        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:128) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at Multiverse-Inventories-4.2.7-pre.jar/com.onarandombox.multiverseinventories.utils.configuration.json.JsonConfiguration.loadConfiguration(JsonConfiguration.java:110) ~[Multiverse-Inventories-4.2.7-pre.jar:?]
        at Multiverse-Inventories-4.2.7-pre.jar/com.onarandombox.multiverseinventories.utils.configuration.json.JsonConfiguration.loadConfiguration(JsonConfiguration.java:131) ~[Multiverse-Inventories-4.2.7-pre.jar:?]
        at Multiverse-Inventories-4.2.7-pre.jar/com.onarandombox.multiverseinventories.FlatFileProfileDataSource.getConfigHandleNow(FlatFileProfileDataSource.java:96) ~[Multiverse-Inventories-4.2.7-pre.jar:?]
        at Multiverse-Inventories-4.2.7-pre.jar/com.onarandombox.multiverseinventories.FlatFileProfileDataSource$ConfigLoader.call(FlatFileProfileDataSource.java:108) ~[Multiverse-Inventories-4.2.7-pre.jar:?]
        at Multiverse-Inventories-4.2.7-pre.jar/com.onarandombox.multiverseinventories.FlatFileProfileDataSource$ConfigLoader.call(FlatFileProfileDataSource.java:99) ~[Multiverse-Inventories-4.2.7-pre.jar:?]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1575) ~[?:?]
[10:04:34 ERROR]: [org.bukkit.configuration.serialization.ConfigurationSerialization] Could not call method 'public static org.bukkit.inventory.meta.ItemMeta org.bukkit.craftbukkit.inventory.SerializableMeta.deserialize(java.util.Map) throws java.lang.Throwable' of class org.bukkit.craftbukkit.inventory.SerializableMeta for deserialization
java.lang.NullPointerException: null
        at java.base/java.util.Objects.requireNonNull(Objects.java:220) ~[?:?]
        at org.bukkit.craftbukkit.inventory.CraftMetaBlockState.getBlockState(CraftMetaBlockState.java:280) ~[paper-1.21.1.jar:1.21.1-123-aebbdc9]
        at org.bukkit.craftbukkit.inventory.SerializableMeta.deserialize(SerializableMeta.java:80) ~[paper-1.21.1.jar:1.21.1-123-aebbdc9]
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
        at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
        at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeViaMethod(ConfigurationSerialization.java:87) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.configuration.serialization.ConfigurationSerialization.deserialize(ConfigurationSerialization.java:129) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeObject(ConfigurationSerialization.java:209) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at Multiverse-Inventories-4.2.7-pre.jar/com.onarandombox.multiverseinventories.utils.configuration.util.SerializationHelper.deserialize(SerializationHelper.java:125) ~[Multiverse-Inventories-4.2.7-pre.jar:?]
        at Multiverse-Inventories-4.2.7-pre.jar/com.onarandombox.multiverseinventories.utils.configuration.util.SerializationHelper.deserialize(SerializationHelper.java:116) ~[Multiverse-Inventories-4.2.7-pre.jar:?]
        at Multiverse-Inventories-4.2.7-pre.jar/com.onarandombox.multiverseinventories.utils.configuration.util.SerializationHelper.deserialize(SerializationHelper.java:116) ~[Multiverse-Inventories-4.2.7-pre.jar:?]
        at Multiverse-Inventories-4.2.7-pre.jar/com.onarandombox.multiverseinventories.utils.configuration.util.SerializationHelper.deserialize(SerializationHelper.java:116) ~[Multiverse-Inventories-4.2.7-pre.jar:?]
        at Multiverse-Inventories-4.2.7-pre.jar/com.onarandombox.multiverseinventories.utils.configuration.util.SerializationHelper.deserialize(SerializationHelper.java:116) ~[Multiverse-Inventories-4.2.7-pre.jar:?]
        at Multiverse-Inventories-4.2.7-pre.jar/com.onarandombox.multiverseinventories.utils.configuration.json.JsonConfiguration.convertMapsToSections(JsonConfiguration.java:75) ~[Multiverse-Inventories-4.2.7-pre.jar:?]
        at Multiverse-Inventories-4.2.7-pre.jar/com.onarandombox.multiverseinventories.utils.configuration.json.JsonConfiguration.loadFromString(JsonConfiguration.java:68) ~[Multiverse-Inventories-4.2.7-pre.jar:?]
        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:128) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at Multiverse-Inventories-4.2.7-pre.jar/com.onarandombox.multiverseinventories.utils.configuration.json.JsonConfiguration.loadConfiguration(JsonConfiguration.java:110) ~[Multiverse-Inventories-4.2.7-pre.jar:?]
        at Multiverse-Inventories-4.2.7-pre.jar/com.onarandombox.multiverseinventories.utils.configuration.json.JsonConfiguration.loadConfiguration(JsonConfiguration.java:131) ~[Multiverse-Inventories-4.2.7-pre.jar:?]
        at Multiverse-Inventories-4.2.7-pre.jar/com.onarandombox.multiverseinventories.FlatFileProfileDataSource.getConfigHandleNow(FlatFileProfileDataSource.java:96) ~[Multiverse-Inventories-4.2.7-pre.jar:?]
        at Multiverse-Inventories-4.2.7-pre.jar/com.onarandombox.multiverseinventories.FlatFileProfileDataSource.processProfileWrite(FlatFileProfileDataSource.java:200) ~[Multiverse-Inventories-4.2.7-pre.jar:?]
        at Multiverse-Inventories-4.2.7-pre.jar/com.onarandombox.multiverseinventories.FlatFileProfileDataSource$FileWriter.call(FlatFileProfileDataSource.java:191) ~[Multiverse-Inventories-4.2.7-pre.jar:?]
        at Multiverse-Inventories-4.2.7-pre.jar/com.onarandombox.multiverseinventories.FlatFileProfileDataSource$FileWriter.call(FlatFileProfileDataSource.java:182) ~[Multiverse-Inventories-4.2.7-pre.jar:?]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1575) ~[?:?]
[10:04:34 ERROR]: [org.bukkit.configuration.serialization.ConfigurationSerialization] Could not call method 'public static org.bukkit.inventory.meta.ItemMeta org.bukkit.craftbukkit.inventory.SerializableMeta.deserialize(java.util.Map) throws java.lang.Throwable' of class org.bukkit.craftbukkit.inventory.SerializableMeta for deserialization
java.lang.NullPointerException: null
        at java.base/java.util.Objects.requireNonNull(Objects.java:220) ~[?:?]
        at org.bukkit.craftbukkit.inventory.CraftMetaBlockState.getBlockState(CraftMetaBlockState.java:280) ~[paper-1.21.1.jar:1.21.1-123-aebbdc9]
        at org.bukkit.craftbukkit.inventory.SerializableMeta.deserialize(SerializableMeta.java:80) ~[paper-1.21.1.jar:1.21.1-123-aebbdc9]
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
        at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
        at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeViaMethod(ConfigurationSerialization.java:87) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.configuration.serialization.ConfigurationSerialization.deserialize(ConfigurationSerialization.java:129) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeObject(ConfigurationSerialization.java:209) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at Multiverse-Inventories-4.2.7-pre.jar/com.onarandombox.multiverseinventories.utils.configuration.util.SerializationHelper.deserialize(SerializationHelper.java:125) ~[Multiverse-Inventories-4.2.7-pre.jar:?]
        at Multiverse-Inventories-4.2.7-pre.jar/com.onarandombox.multiverseinventories.utils.configuration.util.SerializationHelper.deserialize(SerializationHelper.java:116) ~[Multiverse-Inventories-4.2.7-pre.jar:?]
        at Multiverse-Inventories-4.2.7-pre.jar/com.onarandombox.multiverseinventories.utils.configuration.util.SerializationHelper.deserialize(SerializationHelper.java:116) ~[Multiverse-Inventories-4.2.7-pre.jar:?]
        at Multiverse-Inventories-4.2.7-pre.jar/com.onarandombox.multiverseinventories.utils.configuration.util.SerializationHelper.deserialize(SerializationHelper.java:116) ~[Multiverse-Inventories-4.2.7-pre.jar:?]
        at Multiverse-Inventories-4.2.7-pre.jar/com.onarandombox.multiverseinventories.utils.configuration.util.SerializationHelper.deserialize(SerializationHelper.java:116) ~[Multiverse-Inventories-4.2.7-pre.jar:?]
        at Multiverse-Inventories-4.2.7-pre.jar/com.onarandombox.multiverseinventories.utils.configuration.json.JsonConfiguration.convertMapsToSections(JsonConfiguration.java:75) ~[Multiverse-Inventories-4.2.7-pre.jar:?]
        at Multiverse-Inventories-4.2.7-pre.jar/com.onarandombox.multiverseinventories.utils.configuration.json.JsonConfiguration.loadFromString(JsonConfiguration.java:68) ~[Multiverse-Inventories-4.2.7-pre.jar:?]
        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:128) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at Multiverse-Inventories-4.2.7-pre.jar/com.onarandombox.multiverseinventories.utils.configuration.json.JsonConfiguration.loadConfiguration(JsonConfiguration.java:110) ~[Multiverse-Inventories-4.2.7-pre.jar:?]
        at Multiverse-Inventories-4.2.7-pre.jar/com.onarandombox.multiverseinventories.utils.configuration.json.JsonConfiguration.loadConfiguration(JsonConfiguration.java:131) ~[Multiverse-Inventories-4.2.7-pre.jar:?]
        at Multiverse-Inventories-4.2.7-pre.jar/com.onarandombox.multiverseinventories.FlatFileProfileDataSource.getConfigHandleNow(FlatFileProfileDataSource.java:96) ~[Multiverse-Inventories-4.2.7-pre.jar:?]
        at Multiverse-Inventories-4.2.7-pre.jar/com.onarandombox.multiverseinventories.FlatFileProfileDataSource.processProfileWrite(FlatFileProfileDataSource.java:200) ~[Multiverse-Inventories-4.2.7-pre.jar:?]
        at Multiverse-Inventories-4.2.7-pre.jar/com.onarandombox.multiverseinventories.FlatFileProfileDataSource$FileWriter.call(FlatFileProfileDataSource.java:191) ~[Multiverse-Inventories-4.2.7-pre.jar:?]
        at Multiverse-Inventories-4.2.7-pre.jar/com.onarandombox.multiverseinventories.FlatFileProfileDataSource$FileWriter.call(FlatFileProfileDataSource.java:182) ~[Multiverse-Inventories-4.2.7-pre.jar:?]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1575) ~[?:?]
```

### Details
I **did not try** to reproduce my issue on a freshly setup and up-to-date server with the latest version of Multiverse plugins with no other plugins. I run no other server or client mods.

**Description**  
```
NPE from inventory module when moving between MV worlds.
```

**Steps to reproduce**  
```
/mvtp <other world>
- Read console log
```

**Expected behavior**  
```
Clean movement, without NPE.
```

**Comment by SlimeDog** [comment]
This issue must have been resolved with updates to other plugins. It has not occurred for some time.
